### ISSUE TITLE
Why is text-1.2.3.0 not included in lts-9 and lts-10?

### ISSUE THREAD

**Issue by peti** [commercialhaskell/lts-haskell#103]
http://hackage.haskell.org/package/text-1.2.3.0 was released last year, but it's still not included in any LTS package set even though it's a point release. I wonder why that is?

**Comment by bergmark** [comment]
Maybe @DanBurton / @alexeyzab can attempt to upgrade it in the next LTS 10 build? We have an item on the wishlist to be able to add comments about why upper bounds are added to LTS.

**Comment by DanBurton** [comment]
QuickCheck-2.10.1 is out of bounds for:
- text-1.2.3.0 (>=2.7 && < 2.10). No maintainer. @haskell. Used by: test-sui
te

text-1.2.3.0 is out of bounds for:
- sqlite-simple-errors-0.6.0.0 (>=1.2 && < 1.2.3). Joseph Canero <jmc41493@g
mail.com> @caneroj1. @caneroj1. Used by: library, test-suite
- text-all-0.4.1.1 (==1.2.2.*). Artyom <yom@artyom.me> @neongreen. @aelve. U
sed by: library

**Comment by neongreen** [comment]
`text-all`: released 0.4.2.

**Comment by peti** [comment]
Ping @caneroj1.

**Comment by snoyberg** [comment]
Question has been answered, closing.
