### ISSUE TITLE
Upper bounds for LTS 11.12

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/lts-haskell#130]
Cabal-2.0.1.1 (Mikhail Glushenkov <mikhail.glushenkov@gmail.com> @23Skidoo) is out of bounds for:
- [ ] jailbreak-cabal-1.3.3 (==1.20.* || ==1.24.* || >=2.2). Peter Simons <simons@cryp.to> @peti. @peti. Used by: executable

async-2.1.1.1 (Michael Snoyman michael@snoyman.com @snoyberg) is out of bounds for:
- [ ] Agda-2.5.4 (==2.2.*). Andrés Sicard-Ramírez <asr@eafit.edu.co> @asr. @agda. Used by: library

hasql-1.1.1 (Nikita Volkov <nikita.y.volkov@mail.ru> @nikita-volkov) is out of bounds for:
- [ ] hasql-optparse-applicative-0.3.0.3 (==1.3.*). Nikita Volkov <nikita.y.volkov@mail.ru> @nikita-volkov. @sannsyn. Used by: library

hasql-pool-0.4.3.1 (Nikita Volkov <nikita.y.volkov@mail.ru> @nikita-volkov) is out of bounds for:
- [ ] hasql-optparse-applicative-0.3.0.3 (==0.5.*). Nikita Volkov <nikita.y.volkov@mail.ru> @nikita-volkov. @sannsyn. Used by: library

heist-1.0.1.2 (Lucas David Traverso <lucas6246@gmail.com> @ludat) is out of bounds for:
- [ ] snap-1.1.1.0 (==1.1.*). Lucas David Traverso <lucas6246@gmail.com> @ludat. @mightybyte. Used by: library, test-suite

pipes-misc-0.4.0.1 (Louis Pan <louis@pan.me> @louispan) is out of bounds for:
- [ ] pipes-fluid-0.6.0.1 (>=0.5). Louis Pan <louis@pan.me> @louispan. @louispan. Used by: test-suite

transient-0.5.9.2 (Alberto G. Corona <agocorona@gmail.com> @agocorona) is out of bounds for:
- [ ] axiom-0.4.7 (>=0.6.0.1). Alberto G. Corona <agocorona@gmail.com> @agocorona. @agocorona @transient-haskell. Used by: library

transient-universe-0.4.6.1 (Alberto G. Corona <agocorona@gmail.com> @agocorona) is out of bounds for:
- [ ] axiom-0.4.7 (>=0.5.0.0). Alberto G. Corona <agocorona@gmail.com> @agocorona. @agocorona @transient-haskell. Used by: library

**Comment by asr** [comment]
> async-2.1.1.1 (Michael Snoyman michael@snoyman.com @snoyberg) is out of bounds for:
>
>  [ ]  Agda-2.5.4 (==2.2.*). Andrés Sicard-Ramírez asr@eafit.edu.co @asr. @agda. Used by: library

I don't understand why are you asking for supporting `async-2.1.1.1` if support for `async-2.2.1` was required in https://github.com/commercialhaskell/stackage/issues/3268.

**Comment by snoyberg** [comment]
This is for LTS Haskell, which doesn't include major version bumps within a series. As a result of this, we'll need to hold Agda back to an older version. No change is necessary. I'm opening this issue to record why we'll be holding back to an older version.

(Ideally we should have some boilerplate text that explains all this. Opening these kinds of issues is a relatively new thing we do.)

**Comment by asr** [comment]
I see, thanks!

**Comment by snoyberg** [comment]
Good call @DanBurton, I've opened #131 to address it.
