### ISSUE TITLE
Add uom-plugin to lts-11.14

### ISSUE THREAD

**Issue by philderbeast** [commercialhaskell/lts-haskell#136]
The `uom-plugin` [does not build with GHC 8.4.*](https://github.com/adamgundry/uom-plugin/issues/43) possibly because of changes in GHC's constraints solver so we can't yet add it to stackage-nightly. Could you please add it to the latest GHC 8.2.* version of LTS-stackage?

Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have succesfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` is the version of the package you want to get into the LTS series, and `$lts` is the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks

I ran through this sequence of steps and found two [hlint suggestions with NormalForm](https://github.com/adamgundry/uom-plugin/issues/48) that are minor. Please add `uom-plugin` to LTS stackage despite this minor test failure if that is possible.

```
> stack unpack uom-plugin-0.3.0.0
> cd uom-plugin-0.3.0.0/
> stack init --resolver lts-11.14
> stack build --haddock --test --bench --no-run-benchmarks
...
uom-plugin-0.3.0.0: test (suite: hlint)

Progress 63/64: uom-plugin-0.3.0.0src/Data/UnitsOfMeasure/Plugin/NormalForm.hs:150:33:
Suggestion: Use tuple-section
Found:
  \ b -> (b, i)
Why not:
  (, i)
Note: may require `{-# LANGUAGE TupleSections #-}` adding to the top of the file

src/Data/UnitsOfMeasure/Plugin/NormalForm.hs:180:13: Warning: Use sortOn
Found:
  sortBy (comparing (abs . snd))
Why not:
  sortOn (abs . snd)

2 hints
...
uom-plugin-0.3.0.0: Test suite units passed
Completed 64 action(s).
Test suite failure for package uom-plugin-0.3.0.0
    hlint:  exited with: ExitFailure 1
Logs printed to console
```

**Comment by philderbeast** [comment]
After deleting `.stack-work`, `cabal.project`, `cabal.project.freeze` and `**/*.cabal`, I see these `hlint` failures with `lts-14` working with a clone of the repo, the same as seen with a `stack unpack uom-plugin-0.3.0.0`.

```
> stack test uom-plugin:hlint --resolver=lts-11.14
...
Progress 2/3: uom-plugin-0.3.0.0src/Data/UnitsOfMeasure/Plugin/NormalForm.hs:150:33: 
Suggestion: Use tuple-section
Found:
  \ b -> (b, i)
Why not:
  (, i)
Note: may require `{-# LANGUAGE TupleSections #-}` adding to the top of the file

src/Data/UnitsOfMeasure/Plugin/NormalForm.hs:180:13: Warning: Use sortOn
Found:
  sortBy (comparing (abs . snd))
Why not:
  sortOn (abs . snd)

2 hints
```

After deleting `.stack-work`, `cabal.project`, `cabal.project.freeze` and `**/*.cabal` again, I don't see these `hlint` failures with `lts-13`.

```
> stack test uom-plugin:hlint --resolver=lts-11.13
uom-plugin-0.3.0.0: test (suite: hlint)

Progress 2/3: uom-plugin-0.3.0.0No hints

uom-plugin-0.3.0.0: Test suite hlint passed
```

**Comment by bergmark** [comment]
I got those hlint failures while building LTS 11.15, it probably depends on which version of hlint you end up running. I've marked the tests as expected failures, but please see https://www.snoyman.com/blog/2017/11/future-proofing-test-suites
