### ISSUE TITLE
lts-3.22 ghcjs build: broken tagged version dependencies

### ISSUE THREAD

**Issue by MarianJancar** [commercialhaskell/lts-haskell#141]
lts: 3.22
ghcjs: ghcjs-0.1.0.20150924_ghc-7.10.2

[mjancar@gitrig zzz.1]$ stack new dddd --resolver ghcjs-0.1.0.20150924_ghc-7.10.2
Downloading template "new-template" to create project "dddd" in dddd/ ...

The following parameters were needed by the template but not provided: author-email, author-name, category, copyright, github-username
You can provide them in /home/mjancar/.stack/config.yaml, like this:
templates:
  params:
    author-email: value
    author-name: value
    category: value
    copyright: value
    github-username: value
Or you can pass each one as parameters like this:
stack new dddd new-template -p "author-email:value" -p "author-name:value" -p "category:value" -p "copyright:value" -p "github-username:value"

Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- dddd/

Selected resolver: ghcjs-0.1.0.20150924_ghc-7.10.2
Preparing to install GHCJS to an isolated location.
This will not interfere with any system-level installation.
No sha1 or sha256 found in metadata, download hash won't be checked.
Already downloaded.                                      
WARNING: Ignoring out of range dependency (trusting snapshot over Hackage revisions): tagged-0.8.1. semigroupoids requires: >=0.8.5 && <1
ghcjs-prim-0.1.0.0: configure (lib)              
ghcjs-prim-0.1.0.0: build (lib)
semigroupoids-5.0.0.4: configure
ghcjs-prim-0.1.0.0: copy/register
Log files have been written to: /home/mjancar/.stack/programs/x86_64-linux/ghcjs-0.1.0.20150924_ghc-7.10.2/src/.stack-work/logs/
Progress 2/7

--  While building custom Setup.hs for package semigroupoids-5.0.0.4 using:
      /tmp/stack15916/semigroupoids-5.0.0.4/.stack-work/dist/x86_64-linux-tinfo6/Cabal-1.22.4.0/setup/setup --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-1.22.4.0 configure --with-ghc=/home/mjancar/.stack/programs/x86_64-linux/ghc-tinfo6-7.10.2/bin/ghc --with-ghc-pkg=/home/mjancar/.stack/programs/x86_64-linux/ghc-tinfo6-7.10.2/bin/ghc-pkg --with-ghcjs=/home/mjancar/.local/bin/ghcjs --with-ghcjs-pkg=/home/mjancar/.local/bin/ghcjs-pkg --user --package-db=clear --package-db=global --package-db=/home/mjancar/.stack/snapshots/x86_64-linux-tinfo6/lts-3.6/7.10.2/pkgdb --libdir=/home/mjancar/.stack/snapshots/x86_64-linux-tinfo6/lts-3.6/7.10.2/lib --bindir=/home/mjancar/.stack/snapshots/x86_64-linux-tinfo6/lts-3.6/7.10.2/bin --datadir=/home/mjancar/.stack/snapshots/x86_64-linux-tinfo6/lts-3.6/7.10.2/share --libexecdir=/home/mjancar/.stack/snapshots/x86_64-linux-tinfo6/lts-3.6/7.10.2/libexec --sysconfdir=/home/mjancar/.stack/snapshots/x86_64-linux-tinfo6/lts-3.6/7.10.2/etc --docdir=/home/mjancar/.stack/snapshots/x86_64-linux-tinfo6/lts-3.6/7.10.2/doc/semigroupoids-5.0.0.4 --htmldir=/home/mjancar/.stack/snapshots/x86_64-linux-tinfo6/lts-3.6/7.10.2/doc/semigroupoids-5.0.0.4 --haddockdir=/home/mjancar/.stack/snapshots/x86_64-linux-tinfo6/lts-3.6/7.10.2/doc/semigroupoids-5.0.0.4 --dependency=base=base-4.8.1.0-4f7206fd964c629946bb89db72c80011 --dependency=base-orphans=base-orphans-0.4.4-61f87fbe40b70a96b4f01742198bd89e --dependency=bifunctors=bifunctors-5-007f1648d52e47522a17644b5f1ccc3f --dependency=comonad=comonad-4.2.7.2-326dbed78c5926b8f035e3c07a6bb726 --dependency=containers=containers-0.5.6.2-7a88df79ef535718d24bcf01924e95ea --dependency=contravariant=contravariant-1.3.3-ca786de1f8971015ff79769af2deca78 --dependency=distributive=distributive-0.4.4-8ccf7d9b4dba827f6bbdf2f9c6ea65a1 --dependency=semigroups=semigroups-0.16.2.2-ab51ee57739af87b85aa6b9580a50f60 --dependency=tagged=tagged-0.8.1-8fb7724b78ef88e44ca8950c77a173f6 --dependency=transformers=transformers-0.4.2.0-21dcbf13c43f5d8cf6a1f54dee6c5bff --dependency=transformers-compat=transformers-compat-0.4.0.4-3ca5cbcec233c17da785d5f27705643c
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/mjancar/.stack/programs/x86_64-linux/ghcjs-0.1.0.20150924_ghc-7.10.2/src/.stack-work/logs/semigroupoids-5.0.0.4.log

    [1 of 2] Compiling Main             ( /tmp/stack15916/semigroupoids-5.0.0.4/Setup.lhs, /tmp/stack15916/semigroupoids-5.0.0.4/.stack-work/dist/x86_64-linux-tinfo6/Cabal-1.22.4.0/setup/Main.o )
    [2 of 2] Compiling StackSetupShim   ( /home/mjancar/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /tmp/stack15916/semigroupoids-5.0.0.4/.stack-work/dist/x86_64-linux-tinfo6/Cabal-1.22.4.0/setup/StackSetupShim.o )
    Linking /tmp/stack15916/semigroupoids-5.0.0.4/.stack-work/dist/x86_64-linux-tinfo6/Cabal-1.22.4.0/setup/setup ...
    Configuring semigroupoids-5.0.0.4...
    setup: At least the following dependencies are missing:
    tagged >=0.8.5 && <1 && ==0.8.1

**Comment by juhp** [comment]
What were you expecting?  Is this a stack query?

**Comment by snoyberg** [comment]
No answer to question, closing. This does not appear to be related to lts-haskell.
