### ISSUE TITLE
Add inline-c, inline-java and others to lts-12

### ISSUE THREAD

**Issue by facundominguez** [commercialhaskell/lts-haskell#144]
Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have succesfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` is the version of the package you want to get into the LTS series, and `$lts` is the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks

The packages to add are:
* inline-c
* jni
* jvm
* inline-java
* jvm-batching
* jvm-streaming
* sparkle

Thank you.

**Comment by juhp** [comment]
jni fails to build since it can't find libjvm.so in our builder image...
I think we need all the Java `configure-args` from Nightly build-constraints.xml.
(The easiest way to get packages into LTS is via Nightly:)

@snoyberg I am not sure how this should work - does it need a commit to lts-haskell?

**Comment by snoyberg** [comment]
I manually added the `configure-args` to the plan file, and published lts-12.4 with these packages added.
