### ISSUE TITLE
LTS-12.X: Add back dhall-nix and all deps

### ISSUE THREAD

**Issue by domenkozar** [commercialhaskell/lts-haskell#146]
I'd like to add dhall-nix and all dependencies:

- dhall-nix-1.1.5
- hashing-0.1.0.1
- monadlist-0.0.2
- serialise-0.2.0.0
- cborg-0.2.0.0
- hnix-0.5.2

Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have succesfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` is the version of the package you want to get into the LTS series, and `$lts` is the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks

**Comment by juhp** [comment]
You don't want to add it to Nightly?

**Comment by juhp** [comment]
hnix induces:

QuickCheck-2.11.3 is out of bounds for:
- [ ] serialise-0.2.0.0 (>=2.9 && < 2.11). No maintainer. @well-typed. Used by: test-suite

aeson-1.3.1.1 (Adam Bergmark <adam@bergmark.nl> @bergmark) is out of bounds for:
- [ ] serialise-0.2.0.0 (>=0.7 && < 1.3). No maintainer. @well-typed. Used by: test-suite, benchmark

criterion-1.4.1.0 (Ryan Scott <ryan.gl.scott@gmail.com> @RyanGlScott) is out of bounds for:
- [ ] serialise-0.2.0.0 (>=1.0 && < 1.3). No maintainer. @well-typed. Used by: benchmark

store-0.5.0 (Michael Snoyman michael@snoyman.com @snoyberg) is out of bounds for:
- [ ] serialise-0.2.0.0 (==0.4.*). No maintainer. @well-typed. Used by: benchmark

tasty-1.1.0.2 (Roman Cheplyaka <roma@ro-che.info> @feuerbach) is out of bounds for:
- [ ] serialise-0.2.0.0 (>=0.11 && < 0.13). No maintainer. @well-typed. Used by: test-suite

tasty-hunit-0.10.0.1 (Roman Cheplyaka <roma@ro-che.info> @feuerbach) is out of bounds for:
- [ ] serialise-0.2.0.0 (==0.9.*). No maintainer. @well-typed. Used by: test-suite

tasty-quickcheck-0.10 (Roman Cheplyaka <roma@ro-che.info> @feuerbach) is out of bounds for:
- [ ] serialise-0.2.0.0 (>=0.8 && < 0.10). No maintainer. @well-typed. Used by: test-suite

**Comment by domenkozar** [comment]
@juhp I see - how do I reproduce this with stack including multiple packages? The instructions in the issue only work if you're testing a single package addition with condition of all dependency existing already in stackage.

**Comment by juhp** [comment]
I am not sure to be honest.
TBH I don't like the fact that stack insists on a exploded sources for this...

Maybe we can skip the tests for serialise to let these packages in.

**Comment by domenkozar** [comment]
@juhp that would be lovely, at least until new version of serialise is out.

**Comment by domenkozar** [comment]
@juhp anything preventing from doing that?

**Comment by snoyberg** [comment]
Stack doesn't require exploded sources, just add the dependencies to `extra-deps`. But I'm not really a fan of adding a package to LTS when we're intentionally disabling the test suites like this. Any chance you can work with upstream @domenkozar to get the test bounds updated?

**Comment by snoyberg** [comment]
All packages from this list with relaxed enough bounds to be included have been added. Closing the issue for now, please open a new one when bounds have been relaxed.
