### ISSUE TITLE
stack-1.7.1 has bounds failure on LTS-12.1

### ISSUE THREAD

**Issue by domenkozar** [commercialhaskell/lts-haskell#149]
```
$ stack unpack stack-1.7.1
Unpacked stack-1.7.1 to /home/ielectric/stack-1.7.1/
$ cd stack-1.7.1/
$ stack init --resolver lts-12.1
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- ./

Selected resolver: lts-12.1
Resolver 'lts-12.1' does not have all the packages to match your requirements.
    temporary version 1.3 found
        - stack requires >=1.2.1.1 && <1.3
    Using package flags:
        - stack: disable-git-info = False, hide-dependency-versions = False, integration-tests = False, static = False, supported-build = False

This may be resolved by:
    - Using '--solver' to ask cabal-install to generate extra-deps, atop the chosen snapshot.
    - Using '--omit-packages to exclude mismatching package(s).
    - Using '--resolver' to specify a matching snapshot/resolver
```

It's not clear how this can happen, I thought it goes through CI first?

**Comment by juhp** [comment]
Hmm I don't know. At least `stack --resolver lts build stack` resolve okay for me for both 12.1 and 12.2.

**Comment by bergmark** [comment]
This is because of a revision https://hackage.haskell.org/package/stack-1.7.1/revisions/, it works for the snapshot since stack is under `no-revisions`

**Comment by domenkozar** [comment]
@bergmark I find then the instructions for openining an issue in this repository confusing:

1) they don't even work on stack with simple `stack unpack stack-1.7.1 && cd stack-1.7.1 && stack init`

2) they don't work when adding more than one package to LTS

**Comment by bergmark** [comment]
but this issue only occurs if the package is already in the snapshot (and uses `no-revisions`), no need to add it again then!

If you want to add multiple interdependent packages, stack unpack them in a common dir and run the stack commands from there. We could add instructions for that as well, that should be all that's needed.

**Comment by domenkozar** [comment]
Thanks!
