### ISSUE TITLE
Add to lts-12.5: hyraxAbif and bhoogle

### ISSUE THREAD

**Issue by andrevdm** [commercialhaskell/lts-haskell#152]
Packages
  - bhoogle >= 0.1.3.2
  - hyraxAbif >= 0.2.3.5

Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks

**Comment by mihaimaruseac** [comment]
Added, thanks.
