### ISSUE TITLE
Add to lts-12.5 - hvega and ihaskell-hvega

### ISSUE THREAD

**Issue by DougBurke** [commercialhaskell/lts-haskell#153]
Could [hvega-0.1.0.3](https://hackage.haskell.org/package/hvega) and  [ihaskell-hvega-0.1.0.3](https://hackage.haskell.org/package/ihaskell-hvega) (or later versions) be added to LTS 12.5? The failure to build on hackage of ihaskell-hvega is the inability to build the `zeromq4` bindings, but as LTS 12 has `ihaskell` in it, this should (hopefully) not be a problem for Stackage.

Thanks for your time.

Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [X] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks

I had to remove `--haddock` with `--resolver lts-12` as this fell over when building one of the dependencies: `haskell-src-exts-1.20.2`. It worked with `--bench` with `--resolver lts-11`.

**Comment by DougBurke** [comment]
Oops - I guess I need to add it to `nightly` first. Doh. Be back in a second or five.

**Comment by DougBurke** [comment]
I guess this needs to wait for https://github.com/commercialhaskell/stackage/pull/3883 to land.

**Comment by mihaimaruseac** [comment]
Added, thanks.

**Comment by DougBurke** [comment]
Thanks.
