### ISSUE TITLE
stack new yesod-sqlite project fails

### ISSUE THREAD

**Issue by jstr045329** [commercialhaskell/lts-haskell#155]
When I run:

$ stack new my-project yesod-sqlite

I get the following:

Downloading template "yesod-sqlite" to create project "my-project" in my-project/ ...
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- my-project/

Selecting the best among 14 snapshots...

Unable to load cabal files for snapshot

----
Deleting cached snapshot file: /home/jamie/.stack/build-plan/lts-12.6.yaml
Recommendation: try running again. If this fails again, open an upstream issue at:
https://github.com/fpco/lts-haskell/issues/new
----

Unable to parse cabal file for bhoogle-0.1.3.4@sha256:7c54134733cded07e263fced4dc08141f9bc20292d676d218323704b0264aae0,1806: NoParse "license" 7

I'm new to Haskell so having a hard time figuring out what this error is really saying. 

Anybody know what this is about?

**Comment by snoyberg** [comment]
You need to upgrade to a newer version of Stack via `stack upgrade`.

**Comment by snoyberg** [comment]
Based on #156, it looks like upgrading worked.

**Comment by jstr045329** [comment]
After installing libgmp3-dev on Ubuntu, and running stack upgrade, both
commands still give the same error messages.

The commands are:
stack new my-project yesod-sqlite

**Comment by jstr045329** [comment]
and stack install yesod
