### ISSUE TITLE
stack install yesod fails

### ISSUE THREAD

**Issue by jstr045329** [commercialhaskell/lts-haskell#156]
When I run:

$ stack install yesod

I get the following. Anybody know what the real issue is?

Linking /home/jamie/.stack/setup-exe-cache/x86_64-linux-nopie/tmp-Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2 ...
/home/jamie/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld.gold: error: cannot find -lgmp
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(Type.o):integerzmgmp_GHCziIntegerziType_zdwplusBigNatWord_info: error: undefined reference to '__gmpn_add_1'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(Type.o):integerzmgmp_GHCziIntegerziType_zdwminusBigNatWord_info: error: undefined reference to '__gmpn_sub_1'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(Type.o):integerzmgmp_GHCziIntegerziType_zdwtimesBigNatWord_info: error: undefined reference to '__gmpn_mul_1'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(Type.o):integerzmgmp_GHCziIntegerziType_zdwgo_info: error: undefined reference to '__gmpn_add'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(Type.o):integerzmgmp_GHCziIntegerziType_zdwminusBigNat_info: error: undefined reference to '__gmpn_sub'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(Type.o):integerzmgmp_GHCziIntegerziType_zdwtimesBigNat_info: error: undefined reference to '__gmpn_mul'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(Type.o):integerzmgmp_GHCziIntegerziType_neqIntegerzh_info: error: undefined reference to '__gmpn_cmp'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(Type.o):integerzmgmp_GHCziIntegerziType_neqIntegerzh_info: error: undefined reference to '__gmpn_cmp'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(Type.o):integerzmgmp_GHCziIntegerziType_eqIntegerzh_info: error: undefined reference to '__gmpn_cmp'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(Type.o):integerzmgmp_GHCziIntegerziType_eqIntegerzh_info: error: undefined reference to '__gmpn_cmp'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(Type.o):integerzmgmp_GHCziIntegerziType_zdwquotRemBigNatWord_info: error: undefined reference to '__gmpn_divrem_1'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(Type.o):integerzmgmp_GHCziIntegerziType_zdwquotBigNatWord_info: error: undefined reference to '__gmpn_divrem_1'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(Type.o):integerzmgmp_GHCziIntegerziType_orInteger_info: error: undefined reference to '__gmpn_sub_1'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(Type.o):integerzmgmp_GHCziIntegerziType_orInteger_info: error: undefined reference to '__gmpn_sub_1'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(Type.o):integerzmgmp_GHCziIntegerziType_orInteger_info: error: undefined reference to '__gmpn_sub_1'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(Type.o):integerzmgmp_GHCziIntegerziType_zdwquotRemBigNat_info: error: undefined reference to '__gmpn_tdiv_qr'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(Type.o):integerzmgmp_GHCziIntegerziType_remInteger_info: error: undefined reference to '__gmpn_mod_1'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(Type.o):integerzmgmp_GHCziIntegerziType_remInteger_info: error: undefined reference to '__gmpn_mod_1'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(wrappers.o):function integer_gmp_mpn_lshift: error: undefined reference to '__gmpn_lshift'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(wrappers.o):function integer_gmp_gcd_word: error: undefined reference to '__gmpn_gcd_1'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(wrappers.o):function integer_gmp_mpn_gcd_1: error: undefined reference to '__gmpn_gcd_1'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(wrappers.o):function integer_gmp_mpn_gcd_1: error: undefined reference to '__gmpn_gcd_1'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(wrappers.o):function integer_gmp_mpn_gcd: error: undefined reference to '__gmpz_init'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(wrappers.o):function integer_gmp_mpn_gcd: error: undefined reference to '__gmpz_gcd'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(wrappers.o):function integer_gmp_mpn_gcd: error: undefined reference to '__gmpz_clear'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(wrappers.o):function integer_gmp_mpn_tdiv_q: error: undefined reference to '__gmpn_tdiv_qr'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(wrappers.o):function integer_gmp_mpn_tdiv_q: error: undefined reference to '__gmpn_tdiv_qr'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(wrappers.o):function integer_gmp_mpn_tdiv_r: error: undefined reference to '__gmpn_tdiv_qr'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(wrappers.o):function integer_gmp_mpn_and_n: error: undefined reference to '__gmpn_and_n'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(wrappers.o):function integer_gmp_mpn_andn_n: error: undefined reference to '__gmpn_andn_n'
/home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2/integer-gmp-1.0.1.0/libHSinteger-gmp-1.0.1.0.a(wrappers.o):function integer_gmp_mpn_ior_n: error: undefined reference to '__gmpn_ior_n'
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)

--  While building simple Setup.hs using:
      /home/jamie/.stack/programs/x86_64-linux/ghc-nopie-8.2.2/bin/ghc -rtsopts -threaded -clear-package-db -global-package-db -hide-all-packages -package base -main-is StackSetupShim.mainOverride -package Cabal-2.0.1.0 /home/jamie/.stack/setup-exe-src/setup-mPHDZzAJ.hs /home/jamie/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs -o /home/jamie/.stack/setup-exe-cache/x86_64-linux-nopie/tmp-Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2
    Process exited with code: ExitFailure 1

**Comment by snoyberg** [comment]
The error is at the beginning:

```
/home/jamie/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld.gold: error: cannot find -lgmp
```

You need to install the appropriate system-level GMP library. This is not an issue with lts-haskell, so closing here.
