### ISSUE TITLE
In LTS 12, disable native-dns flag for cabal-install

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/lts-haskell#157]
See discussion at https://github.com/haskell/cabal/issues/4883, and PR at https://github.com/commercialhaskell/stackage/pull/3903

**Comment by juhp** [comment]
This needs a PR?

**Comment by snoyberg** [comment]
I was thinking in the next LTS release we could manually edit the `build-plan.yaml` file after it's generated to set the flag appropriately, and then use `NOPLAN=1`.

**Comment by snoyberg** [comment]
Changed in LTS 12.10

**Comment by snoyberg** [comment]
https://github.com/commercialhaskell/stackage-snapshots/blob/4b19bb8e04b0ef27e50dc7a1f18e41c711b2f455/lts/12/10.yaml#L42
