### ISSUE TITLE
Add cayley-client to lts-12, mark as expected test failure

### ISSUE THREAD

**Issue by DanBurton** [commercialhaskell/lts-haskell#166]
Opening on behalf of @MichelBoucey

Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have successfully* run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. Please try running `stack upgrade` and rerunning your commands. If it still fails, please include the output of `stack --version` in this issue.

*The test suite fails as expected -- it requires a running Cayley server -- and should therefore be marked as an expected failure.

**Comment by MichelBoucey** [comment]
`cayley-client-0.4.7` build OK with stack 1.7.1 for LTS-12

**Comment by snoyberg** [comment]
Added to LTS 12.10 https://www.stackage.org/lts-12.10/package/cayley-client-0.4.7

**Comment by MichelBoucey** [comment]
Thanks
