### ISSUE TITLE
Add IPv6DB to lts-12, mark as expected test failure

### ISSUE THREAD

**Issue by DanBurton** [commercialhaskell/lts-haskell#167]
Opening on behalf of @MichelBoucey

Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have successfully* run the following set of commands:

      stack unpack IPv6DB-0.3.0
      cd IPv6DB-0.3.0
      stack init --resolver lts-12
      stack build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. Please try running `stack upgrade` and rerunning your commands. If it still fails, please include the output of `stack --version` in this issue.

*The test suite fails as expected -- it requires a running server -- and should therefore be marked as an expected failure.

**Comment by MichelBoucey** [comment]
`IPv6DB-0.3.1 build OK with stack 1.7.1 for LTS-12

**Comment by snoyberg** [comment]
Added to LTS 12.10 https://www.stackage.org/lts-12.10/package/IPv6DB-0.3.1

**Comment by MichelBoucey** [comment]
Thanks
