### ISSUE TITLE
Add algebraic-graphs-0.2 to LTS-12

### ISSUE THREAD

**Issue by snowleopard** [commercialhaskell/lts-haskell#171]
The `algebraic-graphs` library got dropped from LTS-12, and I'd like to bring it back. The recent version is compatible with `lts-12.10`. Here it is in Stackage Nightly: https://www.stackage.org/nightly-2018-09-29/package/algebraic-graphs-0.2.

Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. Please try running `stack upgrade` and rerunning your commands. If it still fails, please include the output of `stack --version` in this issue.

**Comment by bergmark** [comment]
Done!

**Comment by snowleopard** [comment]
Thanks!
