### ISSUE TITLE
Unable to parse cabal file for bhoogle

### ISSUE THREAD

**Issue by idontgetoutmuch** [commercialhaskell/lts-haskell#174]
I am doing as bid and opening an issue.

```
Deleting cached snapshot file: /root/.stack/build-plan/lts-12.11.yaml
Recommendation: try running again. If this fails again, open an upstream issue at:
https://github.com/fpco/lts-haskell/issues/new
----

Unable to parse cabal file for bhoogle-0.1.3.5@sha256:a3393794b22faabeb564c57f4a9506390b6b97b9792c6b4e130f15bf116099fd,1806: NoParse "license" 7
Exited with code 1
```

**Comment by idontgetoutmuch** [comment]
I changed the nixpkgs git commit and it seemed happy thereafter.

**Comment by espectalll** [comment]
Having the same issue trying to install IHaskell on Debian as instructed on their website, any suggestions?

**Comment by juhp** [comment]
Which version of `stack` btw?

**Comment by andrewufrank** [comment]
I have the same problem. I checked the cabal file - nothing strange in bhoogle.cabal. 
The problem disappeared after `stack upgrade`. 
A better error message would be appreciated....
