### ISSUE TITLE
LTS 12.12 bounds

### ISSUE THREAD

**Issue by bergmark** [commercialhaskell/lts-haskell#175]
Summoner was removed since a revision was filed to it that is incompatible with LTS 12: https://hackage.haskell.org/package/summoner-1.0.6/revisions/

## Bounds issues

JuicyPixels-3.2.9.5 (Vincent Berthoux <vincent.berthoux@gmail.com> @Twinside) is out of bounds for:
- [ ] Rasterific-0.7.4.1 (>=3.3.2). Vincent Berthoux <vincent.berthoux@gmail.com> @Twinside. @Twinside. Used by: library

deque-0.2.4 is out of bounds for:
- [ ] butcher-1.3.2.0 (< 0.2.2). Lennart Spitzner <hexagoxel@hexagoxel.de> @lspitzner. @lspitzner. Used by: library, test-suite

http-api-data-0.3.8.1 (Nickolay Kudasov <nickolay.kudasov@gmail.com> @fizruk) is out of bounds for:
- [ ] servant-auth-server-0.4.1.0 (>=0.3.10 && < 0.4). Domen Kozar <domen@enlambda.com> @domenkozar. @jkarni @phadej. Used by: library

relude-0.1.1 is out of bounds for:
- [ ] summoner-1.0.6 (==0.2.*). Kowainik <xrom.xkov@gmail.com> @ChShersh. @kowainik. Used by: library, executable, test-suite

## Final constraints

CONSTRAINTS='--add-package algebraic-graphs --add-package Spock --constraint "Rasterific<0.7.4.1" --constraint="deque<0.2.2" --constraint "summoner<0" --constraint="servant-auth-server==0.4.0.1" --expect-test-failure jvm-streaming' ./build.sh lts-12.12

**Comment by domenkozar** [comment]
@bergmark could we bump http-api-data to 0.3.10?

**Comment by bergmark** [comment]
These packages need to be updated first:

http-api-data-0.3.10 (Nickolay Kudasov <nickolay.kudasov@gmail.com> @fizruk) is out of bounds for:
- [ ] chatwork-0.1.3.5 (>=0.3.5 && < 0.3.9). Nobutada Matsubara <t12307043@gunma-u.ac.jp> @matsubara0507. @matsubara0507. Used by: library, executable
- [ ] rakuten-0.1.1.5 (>=0.3.5 && < 0.3.9). Nobutada Matsubara <t12307043@gunma-u.ac.jp> @matsubara0507. @matsubara0507. Used by: library
