### ISSUE TITLE
Add groundhog back to LTS 12

### ISSUE THREAD

**Issue by DougBurke** [commercialhaskell/lts-haskell#179]
The groundhog set of packages have been added back to nightly but not LTS 12. Could they be?

- groundhog-0.9.0
- groundhog-inspector-0.9.0
- groundhog-mysql-0.9.0
- groundhog-postgresql-0.9.0.1
- groundhog-sqlite-0.9.0
- groundhog-th-0.9.0.1

(if my copy and paste skills are still up to date).

Ta

**Comment by DanBurton** [comment]
I will attempt to add these to lts-12.15 this weekend.

**Comment by DougBurke** [comment]
Cheers.

**Comment by DanBurton** [comment]
Added in lts-12.16: https://www.stackage.org/diff/lts-12.15/lts-12.16
