### ISSUE TITLE
add the focuslist and gi-vte packages to lts-12

### ISSUE THREAD

**Issue by cdepillabout** [commercialhaskell/lts-haskell#182]
Would it be possible to get the [`focuslist`](http://hackage.haskell.org/package/focuslist) and [`gi-vte`](http://hackage.haskell.org/package/gi-vte) packages into lts-12?

Checklist for adding a package:
- [X] specified the Stackage LTS version in the summary
- [X] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [X] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by cdepillabout** [comment]
Also, it would be great if the [`termonad`](http://hackage.haskell.org/package/termonad-1.0.0.0) package could be added to lts-12.

**Comment by snoyberg** [comment]
`termonad` fails to build:

```
Building library for termonad-1.0.0.0..
[ 1 of 13] Compiling Paths_termonad   ( dist/build/autogen/Paths_termonad.hs, dist/build/Paths_termonad.o )
[ 2 of 13] Compiling Termonad.Prelude ( src/Termonad/Prelude.hs, dist/build/Termonad/Prelude.o )
[ 3 of 13] Compiling Termonad.Gtk     ( src/Termonad/Gtk.hs, dist/build/Termonad/Gtk.o )
[ 4 of 13] Compiling Termonad.Config.Vec ( src/Termonad/Config/Vec.hs, dist/build/Termonad/Config/Vec.o )
[ 5 of 13] Compiling Termonad.Types   ( src/Termonad/Types.hs, dist/build/Termonad/Types.o )
[ 6 of 13] Compiling Termonad.Lenses  ( src/Termonad/Lenses.hs, dist/build/Termonad/Lenses.o )
[ 7 of 13] Compiling Termonad.Term    ( src/Termonad/Term.hs, dist/build/Termonad/Term.o )

src/Termonad/Term.hs:65:5: error:
    Module ‘GI.Gtk’ does not export ‘widgetSetFocusOnClick’
   |
65 |   , widgetSetFocusOnClick
   |     ^^^^^^^^^^^^^^^^^^^^^
```

**Comment by snoyberg** [comment]
Added:

* https://www.stackage.org/lts-12.19/package/focuslist-0.1.0.0
* https://www.stackage.org/lts-12.19/package/gi-vte-2.91.19
