### ISSUE TITLE
Add rosezipper to LTS 12

### ISSUE THREAD

**Issue by bergmark** [commercialhaskell/lts-haskell#184]
Checklist for adding a package:
- [ ] specified the Stackage LTS version in the summary
- [ ] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [ ] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by clojj** [comment]
@bergmark anything else to do here ?

**Comment by bergmark** [comment]
We add packages to LTS manually, so this just serves as a reminder for me when running the build this weekend.

**Comment by mihaimaruseac** [comment]
It is in LTS 12.20
