### ISSUE TITLE
lts-13.0 expected test failures alert

### ISSUE THREAD

**Issue by DanBurton** [commercialhaskell/lts-haskell#191]
The following packages were marked as "expected test failure" for LTS 13.0

* Diff: build failure
* bit-stream: build failure (ping @Bodigrim)
* cereal: build failure
* ghci-hexcalc: test-ghci-hexcalc failure (ping @takenobu-hs)
* heap: build failure
* inline-c: tests failure (ping @facundominguez)
* midi: Test suite timed out (ping @thielema)
* threads: test-threads failure

Some of these failures were also reported on their corresponding issue trackers.

**Comment by amigalemming** [comment]
Where can I see the build logs that show the failure?

**Comment by facundominguez** [comment]
`inline-c` tests pass for me with `lts-13.0`.
