### ISSUE TITLE
add heterocephalus and xml-html-qq to LTS-13

### ISSUE THREAD

**Issue by cdepillabout** [commercialhaskell/lts-haskell#196]
It'd be great to have [heterocephalus](http://hackage.haskell.org/package/heterocephalus) and [xml-html-qq](http://hackage.haskell.org/package/xml-html-qq) added to LTS-13.

I've tested that the latest versions for both of these packages compile with LTS-13.

cc @arowM

------------------------------------------------------------------------
Checklist for adding a package:
- [X] specified the Stackage LTS version in the summary
- [X] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [X] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by snoyberg** [comment]
https://www.stackage.org/lts-13.3/package/heterocephalus-1.0.5.3 and https://www.stackage.org/lts-13.3/package/xml-html-qq-0.1.0.1
