### ISSUE TITLE
Add salak-0.2.1 to LTS-13

### ISSUE THREAD

**Issue by leptonyu** [commercialhaskell/lts-haskell#201]
Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by snoyberg** [comment]
I'm holding off on this and #199 because they conflict, see https://github.com/leptonyu/yam/issues/2

**Comment by snoyberg** [comment]
Perfect, thanks! I'll try to include it in the LTS build I'm running now.

**Comment by snoyberg** [comment]
I just noticed that this is a major version bump. We don't include major version bumps in an LTS minor release.

**Comment by leptonyu** [comment]
Thanks. If I keep yam 0.5.x compatible with both salak 0.1.x and 0.2.x, then yam could update in lts13.4+. Is that right?

**Comment by snoyberg** [comment]
Typically no, we don't include any major version bumps unless there's a
compelling reason to make an exception.

**Comment by leptonyu** [comment]
I mean yam-0.5.7 is compatible with salak-0.1.6, then would yam-0.5.7 be in tls13.4?

**Comment by snoyberg** [comment]
Yes

**Comment by leptonyu** [comment]
Thank you.
