### ISSUE TITLE
Remove/downgrade shelly from LTS, since it doesn't compile at all on Windows

### ISSUE THREAD

**Issue by leohaskell** [commercialhaskell/lts-haskell#202]
The following steps fail on Windows with all lts versions containing shelly-1.8.1.

Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have ~successfully~ run the following set of commands:
```sh
stack unpack shelly-1.8.1
cd shelly-1.8.1
stack init --resolver lts-13.3
stack build --haddock --test --bench --no-run-benchmarks

*FAILS*
```
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by mihaimaruseac** [comment]
Can you post logs of the failure?

**Comment by leohaskell** [comment]
@mihaimaruseac, here you are:

```bash
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for shelly-1.8.1:
    unix needed, but the stack configuration has no specified version  (latest matching version
         is 2.7.2.2)
needed since shelly is a build target.
```

**Comment by mihaimaruseac** [comment]
`unix` means the package can only be built on Unix environments, not on Windows. Which makes sense, since Windows doesn't really follow POSIX standards

**Comment by leohaskell** [comment]
Thank you for the clarification, but previous versions of shelly were working on Windows, they just broke the build process in 1.8.1.

**Comment by mihaimaruseac** [comment]
You're right, I see they added the `unix` dependency only recently. See https://github.com/yesodweb/Shelly.hs/issues/176

**Comment by mihaimaruseac** [comment]
Oh, you already commented there too. Will downgrade version at the end of the week when building the new LTS

**Comment by mihaimaruseac** [comment]
Downgraded to 1.8.0. Thank you
