### ISSUE TITLE
Add postgresql-simple-migration to lts-13 (but expect test failure)

### ISSUE THREAD

**Issue by DanBurton** [commercialhaskell/lts-haskell#203]
Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

Tested locally with lts-13.3 and postgresql-simple-migration-0.1.13.1.

Note, however, that the test suite will fail.

See also: https://github.com/commercialhaskell/stackage/pull/4303

**Comment by mihaimaruseac** [comment]
Added. Thank you
