### ISSUE TITLE
can't create project on solus

### ISSUE THREAD

**Issue by unicornah** [commercialhaskell/lts-haskell#209]
Unable to parse cabal file for base-noprelude-4.12.0.0@sha256:dcd5ece10257f79fa16e207d558b31ab3467b205adae5d1976abdee28b1c8b4a,6845: NoParse "reexported-modules" 42

**Comment by DanBurton** [comment]
Can you give a little more info on what command you ran, and any relevant files? (Also, the output with `--verbose`, perhaps.)

**Comment by bergmark** [comment]
I think you have an old version of stack, try `stack upgrade` (it should install to ~/.local/bin). Please re-open if the problem persists after that!
