### ISSUE TITLE
Add ShellCheck-0.6.0 (or newer) to lts-13

### ISSUE THREAD

**Issue by DanBurton** [commercialhaskell/lts-haskell#213]
Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      lts='13.8'
      package='ShellCheck'
      version='0.6.0'
      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by juhp** [comment]
https://www.stackage.org/lts-13.9/package/ShellCheck-0.6.0
