### ISSUE TITLE
Add esqueleto to lts-13 (maybe expect test failure)

### ISSUE THREAD

**Issue by DanBurton** [commercialhaskell/lts-haskell#215]
Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**On my machine I was not able to get the sqlite tests to pass, purely due to local setup. It may need to be marked as an expected test failure, depending on the stackage build server setup. Everything else was fine.

**Comment by juhp** [comment]
https://www.stackage.org/lts-13.9/package/esqueleto-2.6.0

I think I had to disable haddock too like in Nightly.
