### ISSUE TITLE
Please add enummapset, LambdaHack, Allure to LTS 13

### ISSUE THREAD

**Issue by Mikolaj** [commercialhaskell/lts-haskell#218]
They are already in stackage nightly with the same GHC.

Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [ ] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [ ] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by snoyberg** [comment]
Done:

* https://www.stackage.org/lts-13.11/package/enummapset-0.6.0.1
* https://www.stackage.org/lts-13.11/package/LambdaHack-0.8.3.0
* https://www.stackage.org/lts-13.11/package/Allure-0.8.3.0

**Comment by Mikolaj** [comment]
Thank you!
