### ISSUE TITLE
ekg 0.4.0.15

### ISSUE THREAD

**Issue by agourlay** [commercialhaskell/lts-haskell#219]
`ekg` is present in the [LTS 12](https://www.stackage.org/lts-12.26/package/ekg-0.4.0.15) but it is absent from the LTS 13.

According to the [following build matrix](https://matrix.hackage.haskell.org/#/package/ekg) the library builds on GHC 8.6.3

Could you please add the library in next LTS 13?

**Comment by DanBurton** [comment]
I can vouch for the usual verification step for this. Please also add ekg-json.

(Here's the "repro" output of my usual macro for testing such things, which is essentially the same as the steps as the issue template.)

```bash
stack unpack ekg-0.4.0.15 && cd ekg-0.4.0.15
edit stack.yaml # add the following stack.yaml
stack build --test --bench --no-run-benchmarks --fast
```

```yaml
# stack.yaml
resolver: lts-13.10
extra-deps:
- ekg-json-0.1.0.6

```

**Comment by snoyberg** [comment]
Done https://www.stackage.org/lts-13.11/package/ekg-0.4.0.15
