### ISSUE TITLE
Add cachix, netrc and servant-conduit to LTS-13

### ISSUE THREAD

**Issue by domenkozar** [commercialhaskell/lts-haskell#220]
Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by snoyberg** [comment]
Both `cachix` and `netrc` have bounds issues with LTS 13:

cachix-api-0.1.0.3 (Domen Kozar <domen@enlambda.com> @domenkozar) is out of bounds for:
- [ ] cachix-0.2.0 (>=0.2.0). No maintainer. @cachix. Used by: library, executable, test-suite

tasty-1.2 (Roman Cheplyaka <roma@ro-che.info> @feuerbach) is out of bounds for:
- [ ] netrc-0.2.0.0 (>=0.10 && < 1.1). No maintainer. @hvr. Used by: test-suite

**Comment by domenkozar** [comment]
need to lift cachix-api bound and disable tests for netrc.

**Comment by snoyberg** [comment]
We don't typically include major versions bumps mid-cycle for an LTS release, or disable tests like that. We can do it if there's specific motivation given though, can you clarify?

**Comment by domenkozar** [comment]
cachix-api package reflects HTTP specification of cachix.org, so it's currently out of date.

**Comment by DanBurton** [comment]
Given `cachix` is the only known revdep of `cachix-api`, I think it's fair to make an exception and bump it. Once cachix-api gets more downstream users, then we'll have to think more carefully about bringing in a major bump for it mid-lts.

Skipping tests for `netrc` should be fine, though of course it would be preferable to instead make the test suite compatible w/ latest tasty.

**Comment by snoyberg** [comment]
I just forgot to update this issue, sorry. I included these in lts-13.12:

* https://www.stackage.org/lts-13.12/package/cachix-0.2.0
* https://www.stackage.org/lts-13.12/package/netrc-0.2.0.0
* https://www.stackage.org/lts-13.12/package/servant-conduit-0.15
