### ISSUE TITLE
lts-13.17 constraints

### ISSUE THREAD

**Issue by DanBurton** [commercialhaskell/lts-haskell#225]
The following constraints were added as of lts-13.17, for the following reasons:

## doctest-discover-configurator < 0

Not sure why this is needed since this does package does not appear in any prior snapshots.

## rio < 0.1.9.0

Ping @snoyberg 

Due to build failures with `stack` (@borsboom) and `etc` (@roman) as described in https://github.com/commercialhaskell/stackage/issues/4479

**Comment by juhp** [comment]
I add to add that constraint to lts-13.18 too somehow - weird
