### ISSUE TITLE
Add Chart, Chart-diagrams, and diagrams-postscript to LTS-13

### ISSUE THREAD

**Issue by bravit** [commercialhaskell/lts-haskell#226]
Checklist for adding a package:
- [X] specified the Stackage LTS version in the summary
- [X] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      mkdir test-chart && cd test-chart
      stack unpack Chart-1.9.1
      stack unpack Chart-diagrams-1.9.2
      stack unpack diagrams-postscript-1.4.1
      stack init --resolver lts-13
      stack build --haddock --test --bench --no-run-benchmarks
- [X] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

The same packages have been already added to Nightly:
https://www.stackage.org/nightly-2019-04-15/package/Chart-1.9.1
https://www.stackage.org/nightly-2019-04-15/package/Chart-diagrams-1.9.2
https://www.stackage.org/nightly-2019-04-15/package/diagrams-postscript-1.4.1

**Comment by juhp** [comment]
Forgot to close this.
They should all be in lts-13.18.
