### ISSUE TITLE
Add cyclotomic-1.0 to lts-13

### ISSUE THREAD

**Issue by walck** [commercialhaskell/lts-haskell#230]
Checklist for adding a package:
- [ ] specified the Stackage LTS version in the summary
- [ ] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [ ] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

Please add cyclotomic-1.0 to lts-13.

**Comment by alexeyzab** [comment]
Added in lts-13.23: https://www.stackage.org/lts-13.23/package/cyclotomic-1.0
