### ISSUE TITLE
Why LTS-13 doesn't include unordered-containers-0.2.10.0

### ISSUE THREAD

**Issue by phadej** [commercialhaskell/lts-haskell#232]
https://github.com/commercialhaskell/stackage/issues/4598

**Comment by DanBurton** [comment]
I do see this in the `current-plan.yaml` file for unordered-containers:

      '>=0.2.9.0 && <0.2.10.0'

I had a lot of other issues to deal with for lts-13.25, so I did not attempt to relax with the constraint to `< 0.3`.

**Comment by juhp** [comment]
Should be in lts-13.26
