### ISSUE TITLE
add TypeCompose, spatial-math, not-gloss, and learn-physics to lts-13

### ISSUE THREAD

**Issue by walck** [commercialhaskell/lts-haskell#233]
Checklist for adding a package:
- [ ] specified the Stackage LTS version in the summary
- [ ] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [ ] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by DanBurton** [comment]
Done in lts-13.25; thanks for the request!

* https://www.stackage.org/lts-13.25/package/TypeCompose-0.9.14
* https://www.stackage.org/lts-13.25/package/spatial-math-0.5.0.1
* https://www.stackage.org/lts-13.25/package/not-gloss-0.7.7.0
* https://www.stackage.org/lts-13.25/package/learn-physics-0.6.4
