### ISSUE TITLE
add rg to lts-13

### ISSUE THREAD

**Issue by cdornan** [commercialhaskell/lts-haskell#234]
Checklist for adding a package:
- [X] specified the Stackage LTS version in the summary
- [X] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [X] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

Thanks!

**Comment by DanBurton** [comment]
Done in lts-13.25. Cheers!

* https://www.stackage.org/lts-13.25/package/rg-1.4.0.0
