### ISSUE TITLE
Document connection between GHC version numbers and LTS version numbers

### ISSUE THREAD

**Issue by andreasabel** [commercialhaskell/lts-haskell#237]
The README should say something how to find the last LTS release for a given GHC version.  I found https://github.com/commercialhaskell/stackage/wiki/Stackage-LTS-Releases so maybe this could be linked from the README, for example.

**Comment by snoyberg** [comment]
This information is available on stackage.org, in the section "Latest LTS per GHC version". A PR to update docs would definitely be welcome.

**Comment by andreasabel** [comment]
Thanks indeed: https://www.stackage.org/
Ok, I can try to put this into a PR.

**Comment by cdornan** [comment]
Closing &mdash; please reopen if you think there is something else we should be doing here.
