### ISSUE TITLE
LTS-14: add mixpanel-client, netrc

### ISSUE THREAD

**Issue by domenkozar** [commercialhaskell/lts-haskell#238]
Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by domenkozar** [comment]
Need to fix cachix/mixpanel-client.

**Comment by juhp** [comment]
Do you want to keep this open?

**Comment by domenkozar** [comment]
I'd prefer to add mixpanel-client and netrc until cachix is fixed.

**Comment by juhp** [comment]
Apologies this didn't make lts-14.2...

**Comment by snoyberg** [comment]
netrc also has an overly strict upper bound:

tasty-1.2.3 (Roman Cheplyaka <roma@ro-che.info> @feuerbach) is out of bounds for:
- [ ] netrc-0.2.0.0 (>=0.10 && < 1.1). No maintainer. @hvr. Used by: test-suite

**Comment by domenkozar** [comment]
Needs tests disabled.

**Comment by snoyberg** [comment]
We don't typically add new packages to LTS or Nightly with tests disabled unless it's for a specific CI reason (like needing a running database).

**Comment by domenkozar** [comment]
Upstream won't fix the bounds and the package hasn't changed in 4 years.

**Comment by snoyberg** [comment]
OK, I'll include it since it's already in LTS 13 and nightly.

**Comment by snoyberg** [comment]
mixpanel-client doesn't compile:

```
--  While building package mixpanel-client-0.2.0 using:
      /var/stackage/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 build lib:mixpanel-client test:mixpanel-test test:readme --ghc-options ""
    Process exited with code: ExitFailure 1
    Logs have been written to: /var/stackage/work/unpack-dir/.stack-work/logs/mixpanel-client-0.2.0.log

    Preprocessing library for mixpanel-client-0.2.0..
    Building library for mixpanel-client-0.2.0..
    [5 of 5] Compiling MixPanel
    
    /var/stackage/work/unpack-dir/unpacked/mixpanel-client-0.2.0-de889246b50b1e05dd2344b2d11c8c6b2c133623fab3824485b0c055921689b9/src/MixPanel.hs:42:18: error:
        Not in scope: type constructor or class ‘ServantError’
        A data constructor of that name is in scope; did you mean DataKinds?
       |
    42 |   = ServantError ServantError
       |                  ^^^^^^^^^^^^
```

**Comment by domenkozar** [comment]
Seems to be a brown-paper-bag release, I've just uploaded 0.2.1.

**Comment by mihaimaruseac** [comment]
mixpanel-client is not in current nightly
