### ISSUE TITLE
Why is lts-14.1 on stackage.org but not here?

### ISSUE THREAD

**Issue by m4lvin** [commercialhaskell/lts-haskell#239]
https://www.stackage.org/lts-14.1 was published five days ago, but there is no `lts-14.1.yaml` in this repository. This makes my CI scripts fail with a 404 on https://raw.githubusercontent.com/fpco/lts-haskell/master/lts-14.1.yaml :thinking:

**Comment by snoyberg** [comment]
That's because we're moving over to a new repo, stackage-snapshots. The lts-haskell repo is being bulk generated for legacy reasons. I've just pushed a commit which adds lts-14.1.yaml

**Comment by bwbaugh** [comment]
Had the same issue, which has since been resolved. Thanks!

**Comment by snoyberg** [comment]
Great! Closing.
