### ISSUE TITLE
add PyF to lts-14

### ISSUE THREAD

**Issue by guibou** [commercialhaskell/lts-haskell#241]
Checklist for adding a package:
- [X] specified the Stackage LTS version in the summary
- [X] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [X] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

Progress tracked in: https://github.com/guibou/PyF/issues/38

**Comment by mihaimaruseac** [comment]
We need to fix tests first in nightly: https://github.com/commercialhaskell/stackage/issues/4783

**Comment by guibou** [comment]
Seems fixed: https://github.com/commercialhaskell/stackage/issues/4783

**Comment by bergmark** [comment]
Added in lts-14.5!
