### ISSUE TITLE
Add servant-rawm-0.3.1.0 to LTS 14

### ISSUE THREAD

**Issue by torgeirsh** [commercialhaskell/lts-haskell#242]
servant-rawm was removed from Stackage for incompatibility, but it has since been fixed in 0.3.1.0, and was [added back to Stackage master](https://github.com/commercialhaskell/stackage/pull/4768). Could it be added to LTS 14 as well? I've verified that it builds with resolver lts-14.3 as per instructions in the checklist.

**Comment by mihaimaruseac** [comment]
Added to 14.4, thank you.
