### ISSUE TITLE
lts-14.4 is released, but YAML file is missing here

### ISSUE THREAD

**Issue by fosskers** [commercialhaskell/lts-haskell#243]
As such, CI systems that expect this path to exist and call for it are failing.

**Comment by snoyberg** [comment]
I've restarted the legacy conversion job. Ultimately these files will no longer be generated though, so migrating to Stack 2 is the best long-term solution (or pinning to specific LTS releases).

**Comment by fosskers** [comment]
Ah gotcha. In that case it's that the `stack` version provided by the latest official `haskell` docker image doesn't yet include Stack 2.

**Comment by snoyberg** [comment]
Got it
