### ISSUE TITLE
Add libssh2 to LTS-13

### ISSUE THREAD

**Issue by hkailahi** [commercialhaskell/lts-haskell#245]
Checklist for adding a package:
- [X] specified the Stackage LTS version in the summary
- [X] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack libssh2-0.2.0.7
      cd libssh2-0.2.0.7
      stack init --resolver lts-13
      stack build --haddock --test --bench --no-run-benchmarks
- [X] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by juhp** [comment]
Have you considered lts-14 or Nightly btw?

**Comment by hkailahi** [comment]
Sorry for the delayed response - I'm now of the opinion that this library shouldn't be added.

I realized that the reason I was able to build because I had `libssh2` installed and configured (`libssh2` on OS X and `libssh2-1-dev` on Ubuntu). Since I don't this is a reasonable dependency to assume, I'm going to close this issue. Thanks!
