### ISSUE TITLE
lts-14.6 add replace-megaparsec, replace-attoparsec

### ISSUE THREAD

**Issue by jamesdbrock** [commercialhaskell/lts-haskell#246]
Please include these packages in __`lts-14.6`__

* `replace-megaparsec`
* `replace-attoparsec`

Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by alexeyzab** [comment]
Added: [replace-megaparsec](https://www.stackage.org/lts-14.6/package/replace-megaparsec-1.1.3.0), [replace-attoparsec](https://www.stackage.org/lts-14.6/package/replace-attoparsec-1.0.1.0)
