### ISSUE TITLE
lts-14.7 replace-megaparsec, replace-attoparsec

### ISSUE THREAD

**Issue by jamesdbrock** [commercialhaskell/lts-haskell#248]
The packages __replace-megaparsec__ and __replace-attoparsec__ were added to __lts-14.6__ #246 but dropped out of __lts-14.7__ for some reason that I can't figure out.

I've re-run the following checklist with __stack 2.1.3__ and it passes. I don't see any GitHub alerts for me. I can't find the __lts-14.7__ build log. Why were these packages dropped, and what should I do?

Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by juhp** [comment]
https://www.stackage.org/lts-14.8/package/replace-megaparsec-1.1.4.0
https://www.stackage.org/lts-14.8/package/replace-attoparsec-1.0.2.0
