### ISSUE TITLE
servant-rawm has disappeared from LTS 14

### ISSUE THREAD

**Issue by torgeirsh** [commercialhaskell/lts-haskell#250]
servant-rawm was added back into LTS 14.4 in #242, but it has since disappeared, and I can't find any information about why. The latest version (0.3.2.0) builds with LTS 14.7, so it would be great if it could be added again.

**Comment by DanBurton** [comment]
How odd. From the diff it looks like this is the only package that has disappeared.

https://www.stackage.org/diff/lts-14.4/lts-14.7

I'll check w/ the other curators to see if this was intentional or not. (It might be a flaw in our build process.)

**Comment by qrilka** [comment]
@DanBurton I wonder how could that package even appear in 14.4 - every one of LTS-14 snapshots contain `range: <0` for the packages, e.g. https://github.com/commercialhaskell/stackage-constraints/blob/master/lts/14/4.yaml#L14265
Looks like some problem in the workflow

**Comment by torgeirsh** [comment]
Any news on this? Will it be back for LTS 14.8?

**Comment by juhp** [comment]
https://www.stackage.org/lts-14.8/package/servant-rawm-0.3.2.0
