### ISSUE TITLE
[LTS 14] add amazonka-*

### ISSUE THREAD

**Issue by DanBurton** [commercialhaskell/lts-haskell#252]
Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [ ] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

I've checked `amazonka-core-1.6.1` with the instructions above. I haven't checked the rest, but this would suggest that `amazonka` and all of the `amazonka-BLAH` packages can probably be re-enabled.

See also: https://github.com/brendanhay/amazonka/issues/532

**Comment by DanBurton** [comment]
For some idea of the laundry list of packages that could be added, see: https://github.com/commercialhaskell/stackage/pull/4889

**Comment by juhp** [comment]
Apologies but this will have to wait for the next build..

**Comment by mihaimaruseac** [comment]
Tried so today, but

```
      /var/stackage/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 build lib:amazonka-directconnect test:amazonka-directconnect-test --ghc-options ""
    Process exited with code: ExitFailure 1
    Logs have been written to: /var/stackage/work/unpack-dir/.stack-work/logs/amazonka-directconnect-1.6.1.log

    Preprocessing library for amazonka-directconnect-1.6.1..
    Building library for amazonka-directconnect-1.6.1..
    ghc: panic! (the 'impossible' happened)
      (GHC version 8.6.5 for x86_64-unknown-linux):
        Ix{Int}.index: Index (0) out of range ((0,-1))
```

CC @brendanhay

**Comment by mihaimaruseac** [comment]
The other packages have been added

**Comment by vaclavsvejcar** [comment]
It looks that `amazonka-` packages are missing again in latest _LTS-14.13_ (see https://www.stackage.org/diff/lts-14.12/lts-14.13)
