### ISSUE TITLE
[LTS 14] add morpheus-graphql

### ISSUE THREAD

**Issue by nalchevanidze** [commercialhaskell/lts-haskell#253]
Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack morpheus-graphql-0.4.0
      cd morpheus-graphql-0.4.0
      stack init --resolver lts-14
      stack build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by mihaimaruseac** [comment]
It should first be on stackage nightly. Please open a [PR](https://github.com/commercialhaskell/stackage/pulls) to add it to `build-constraints.yaml`

**Comment by nalchevanidze** [comment]
so i fixed bug with 8.8.1 and now it works with nightly too.

```sh
stack unpack morpheus-graphql-0.6.2
cd morpheus-graphql-0.6.2
stack init --resolver lts-14
stack build --haddock --test --bench --no-run-benchmarks
```

```sh
stack unpack morpheus-graphql-0.6.2
stack init --resolver nightly
stack build --resolver nightly --haddock --test --bench --no-run-benchmarks
```

both of them was run successfully.

@mihaimaruseac  sorry i did not clearly understand what i should do on stackage?

**Comment by nalchevanidze** [comment]
there is a PR https://github.com/commercialhaskell/stackage/pull/4960

**Comment by bergmark** [comment]
Done.
