### ISSUE TITLE
LTS 14: add PyF

### ISSUE THREAD

**Issue by guibou** [commercialhaskell/lts-haskell#254]
Checklist for adding a package:
- [X] specified the Stackage LTS version in the summary
- [X] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [X] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

Additional question: `PyF` was in `lts-14.5` but not in the following lts (`14.6` to `14.10`). I received no notification about the removal. Did I missed a step to keep `PyF` inside the lts?

**Comment by mihaimaruseac** [comment]
This seems like a bug in our release process, sorry about that. Will investigate why it got dropped

**Comment by mihaimaruseac** [comment]
The bug seems to be similar to https://github.com/commercialhaskell/curator/issues/5

**Comment by bergmark** [comment]
PyF is back in 14.12.

**Comment by bergmark** [comment]
It disappeared again in 14.13 :-/

**Comment by mihaimaruseac** [comment]
Back in, https://www.stackage.org/lts-14.18/package/PyF-0.8.1.2

**Comment by guibou** [comment]
It disappeared again in `14.19`
