### ISSUE TITLE
Add back forma

### ISSUE THREAD

**Issue by cdornan** [commercialhaskell/lts-haskell#255]
I deleted it because the tests are now failing on forma-1.1.2 due to a severe shortage of time but it should probably be restored in the next run.

**Comment by mrkkrp** [comment]
I released `forma-1.1.3` and the tests should pass now.

**Comment by mihaimaruseac** [comment]
`forma-1.1.3` is already in LTS 14.17 https://www.stackage.org/lts-14.17/package/forma-1.1.3
