### ISSUE TITLE
[LTS 14] re-enable support of morpheus-graphql 

### ISSUE THREAD

**Issue by nalchevanidze** [commercialhaskell/lts-haskell#256]
Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack morpheus-graphql-0.7.0
      cd morpheus-graphql-0.7.0
      stack init --resolver lts-14
      stack build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

`morpheus-graphql` was t removed from ts-14.14. Stackage Nightly still supports it.

may i ask why was it removed?

**Comment by mihaimaruseac** [comment]
https://www.stackage.org/lts-14.18/package/morpheus-graphql-0.8.0
