### ISSUE TITLE
[LTS 14] return tidal to lts-14

### ISSUE THREAD

**Issue by yaxu** [commercialhaskell/lts-haskell#258]
Checklist for adding a package:
- [X] specified the Stackage LTS version in the summary
- [X] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack tidal-1.4.5
      cd tidal-1.4.5
      stack init --resolver lts-14
      stack build --haddock --test --bench --no-run-benchmarks
- [X] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

thanks!

**Comment by mihaimaruseac** [comment]
https://www.stackage.org/lts-14.18/package/tidal-1.4.5

**Comment by yaxu** [comment]
Thanks @mihaimaruseac !
