### ISSUE TITLE
Unable to parse cabal file for Allure-0.9.5.0 ..

### ISSUE THREAD

**Issue by robstewart57** [commercialhaskell/lts-haskell#261]
- [X ] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

I'm using to use LSP, haskell-mode, and ghcide. In emacs when loading a file in my project I'm seeing:

```
Suspicious state from syntax checker haskell-stack-ghc: Flycheck checker haskell-stack-ghc returned non-zero exit code 1, but its output contained no errors: Unable to load cabal files for snapshot

----
Deleting cached snapshot file: /home/rob/.stack/build-plan/lts-14.21.yaml
Recommendation: try running again. If this fails again, open an upstream issue at:
https://github.com/fpco/lts-haskell/issues/new
----

Unable to parse cabal file for Allure-0.9.5.0@sha256:ae8e3563ebe6cc38b656c5e27d28543128268fd69ae206a1fdc47f2d2c5d5f40,7633: NoParse "build-depends" 137

Try installing a more recent version of haskell-stack-ghc, and please open a bug report if the issue persists in the latest release.  Thanks!
```

stack.yaml contents:

```
resolver: lts-14.21
packages:
- .
```

Stack version:

```
stack --version
Version 2.2.0, Git revision c3c33b61a4d5c286a6718550d285305270ba4bf0 PRE-RELEASE x86_64 hpack-0.31.2
```

My emacs configuration:

```
  (use-package flycheck
    :ensure t
    :init
    (global-flycheck-mode t))
  (use-package yasnippet
    :ensure t)
  (use-package lsp-mode
    :ensure t
    :hook (haskell-mode . lsp)
    :commands lsp)
  (use-package lsp-ui
    :ensure t
    :commands lsp-ui-mode)
  (use-package lsp-haskell
   :ensure t
   :config
   (setq lsp-haskell-process-path-hie "ghcide")
   (setq lsp-haskell-process-args-hie '())
  )
```

I'm not sure how to reproduce this error outside Emacs, or how to fix it.

**Comment by juhp** [comment]
I can't quite remember if I ran into something like this earlier with ghcide..
(I switched from lsp-mode to eglot fwiw).
I suspect this is either a stack or ghcide (or you using the release btw?) issue.
If you can't reproduce outside ghcide I think it is probably not a problem with Stackage LTS.

**Comment by robstewart57** [comment]
Thankss @juhp I took a closer looks.

Turns out that Emacs was using `/usr/local/bin/stack`, which was version 1.6.5, rather than `~/.local/bin/stack` which is 2.2.0. The issue has gone away. Thanks again.

**Comment by AubreySLavigne** [comment]
I ran into the same error, but the cause was a legit out-of-date version of stack.  The following resolved my issue:

`stack upgrade --binary-only`
