### ISSUE TITLE
Solve the random removal of PyF from lts

### ISSUE THREAD

**Issue by guibou** [commercialhaskell/lts-haskell#265]
I'd like to get PyF back in the lts 14 (`14.24` if possible).

PyF was added in #241 to `14.5`, then again in #254 for `14.12` and removed again since `lts-14.13` and added again in `14.18` and it disappeared again in `14.19`.

Is there something I can do to ensure `PyF` stays in each `lts`? I don't understand the reasons why it is removed and I receive no notification (either mail / github) for the removal.

Checklist for adding a package:
- [X] specified the Stackage LTS version in the summary
- [X] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [X] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by mihaimaruseac** [comment]
We cannot rebuild an old LTS, but I will try to build one last LTS 14 which includes PyF before building LTS 15.

**Comment by mihaimaruseac** [comment]
Also, I'll try to debug why this happens (although it takes at least 20 hours to get something back :-/)

**Comment by qrilka** [comment]
@mihaimaruseac I think the problem is that `PyF` wasn't in build-constraints when lts-14 was started (was removed just before that in #4783) and curator reuses build-constraints from previus minor version of LTS, see https://github.com/commercialhaskell/curator/blob/master/app/Main.hs#L120
and https://github.com/commercialhaskell/stackage-constraints/tree/master/lts/14 doesn't seem to contain any `PyF` version at all. Do packages get added into intermediate LTS version? I think @snoyberg told me that this shouldn't happen when I was implementing the new curator version.

**Comment by mihaimaruseac** [comment]
They do afaik, if they build in nightly.

If I recall correctly, the old system would take the packages from nightly, intersect them with the packages from the previous LTS minor and only then add the additional constraints.

But thank you for the pointers. Makes checking this must faster.

**Comment by snoyberg** [comment]
The old tool didn't do anything special with nightly, we just had a convention to only add packages if they were added to LTS.

@qrilka apologies for confusion from me. We do occasionally add new packages inside an LTS run.

**Comment by qrilka** [comment]
Then I suppose some tool/workflow changes are required to take such cases into account and to prevent issues like this one. But I'm stating the obvious probably.

**Comment by snoyberg** [comment]
@qrilka and I met and figured out the workflow changes necessary. We've updated the scripts and docs here: https://github.com/commercialhaskell/stackage/commit/c9240400cc64770504413faa60f366d3c745ac69

**Comment by mihaimaruseac** [comment]
`PyF` included in both [LTS-14.26](https://www.stackage.org/lts-14.26) and [LTS-14.27](https://www.stackage.org/lts-14.27)

I think the issue with the random removal is fully solved now.

**Comment by guibou** [comment]
Thank you!
