### ISSUE TITLE
Add serverless-haskell to LTS 15

### ISSUE THREAD

**Issue by koterpillar** [commercialhaskell/lts-haskell#268]
Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by bergmark** [comment]
Sorry, I messed up something when adding this it seems. Maybe i just didn't add the package :D

Hopefully @alexeyzab can add it during the next LTS build!

**Comment by alexeyzab** [comment]
Added in lts-15.2: https://www.stackage.org/lts-15.2/package/serverless-haskell-0.10.1
