### ISSUE TITLE
[lts15] add resolv

### ISSUE THREAD

**Issue by juhp** [commercialhaskell/lts-haskell#269]
Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [ ] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks

The testsuite needs to be skipped due to requiring `tasty < 1.2`.

**Comment by bergmark** [comment]
@juhp resolv is not in nightly

**Comment by bergmark** [comment]
oops n/m i misread!

**Comment by bergmark** [comment]
Done
