### ISSUE TITLE
LTS-15: add inline-c-cpp, jose, elm2nix, mixpanel-client, systemd, servan-auth-server, servant-auth, servant-auth-swagger

### ISSUE THREAD

**Issue by domenkozar** [commercialhaskell/lts-haskell#270]
Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

Based on https://github.com/commercialhaskell/stackage/pull/5177

**Comment by alexeyzab** [comment]
Added all of these in lts-15.2: https://www.stackage.org/lts-15.2
