### ISSUE TITLE
Constraints for LTS 15.1

### ISSUE THREAD

**Issue by bergmark** [commercialhaskell/lts-haskell#271]
doclayout-0.2.0.1 ([changelog](http://hackage.haskell.org/package/doclayout-0.2.0.1/changelog)) (John MacFarlane <jgm@berkeley.edu> @jgm) is out of bounds for:
- [ ] pandoc-2.9.2 (>=0.3 && < 0.4). John MacFarlane <jgm@berkeley.edu> @jgm. @jgm. Used by: library

Action: Added `pandoc < 2.9.2` constraint

fusion-plugin-types (not present) depended on by:
- [x] streamly-0.7.1 (>=0.1 && < 0.2). Harendra Kumar <harendra.kumar@gmail.com> @harendra-kumar. @composewell. Used by: library

Action: Added fusion-plugin-types

massiv-0.4.5.0 ([changelog](http://hackage.haskell.org/package/massiv-0.4.5.0/changelog)) (Alexey Kuleshevich <lehins@yandex.ru> @lehins) is out of bounds for:
- [ ] massiv-test-0.1.3 (>=0.5.0). Alexey Kuleshevich <lehins@yandex.ru> @lehins. @lehins. Used by: library

Action: Added `massiv-test < 0.1.3` constraint

Also added `resolv` @juhp

**Comment by jgm** [comment]
I don't understand why doclayout 0.3 (which has been out since January) wasn't included in lts-15.
But I guess it's too late to change that now.

**Comment by cdornan** [comment]
@jgm: sorry, the key to getting a package into lts is getting it into nightly as we cut a new lts-n from nightly. Thereafter we respect the PVP in not major (potentially breaking) x.y bump of an included package.

Nightly is on doclayout-0.2.0.1 -- we need to get it onto 0.3 on nightly first, [which we should be able to do soon](https://github.com/commercialhaskell/stackage/issues/5181).

**Comment by mihaimaruseac** [comment]
doclayout 0.3 is now on nightly
