### ISSUE TITLE
Add 'colourista-0.0.0.0' to LTS 15

### ISSUE THREAD

**Issue by chshersh** [commercialhaskell/lts-haskell#275]
Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack colourista-0.0.0.0
      cd colourista-0.0.0.0
      stack init --resolver lts-15.4
      stack build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by juhp** [comment]
This should be in lts-15.5.
