### ISSUE TITLE
Add hpack-0.33.0 to LTS 15

### ISSUE THREAD

**Issue by DanBurton** [commercialhaskell/lts-haskell#278]
Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by mihaimaruseac** [comment]
It is not on nightly yet, due to https://github.com/sol/hpack/issues/371

I'll try unblocking and testing on nightly

**Comment by mihaimaruseac** [comment]
[Added to LTS])(https://www.stackage.org/lts-15.8/package/hpack-0.33.0) will manually add to nightly
