### ISSUE TITLE
Add registry-0.1.7.1 to LTS-15

### ISSUE THREAD

**Issue by symbiont-eric-torreborre** [commercialhaskell/lts-haskell#279]
Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by mihaimaruseac** [comment]
It should be first included into nightly. But it is not

**Comment by mihaimaruseac** [comment]
[Added to LTS](https://www.stackage.org/lts-15.8/package/registry-0.1.7.1#changes) Will manually add to nightly

**Comment by etorreborre** [comment]
Thanks, I did no know about adding to nightly first. Maybe there should be a checklist item mentioning this and re-directing to https://github.com/commercialhaskell/stackage?
