### ISSUE TITLE
Add MissingH-1.4.3.0

### ISSUE THREAD

**Issue by DanBurton** [commercialhaskell/lts-haskell#280]
Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by bergmark** [comment]
I re-enabled MissingH in nightly but errorcall-eq-instance wasn't commented out so I don't have a maintainer.

**Comment by cdornan** [comment]
@DanBurton `errorcall-eq-instance` looks like history and is [deprecated on Hackage](https://hackage.haskell.org/package/errorcall-eq-instance). Going by the blurb it introduces orphans now covered by base &mdash; should we be introducing it into an lts?

I propose to add MissingH to lts-15 and close the issue. If anybody knows of a good reason to add `errorcall-eq-instance` then could they raise another issue explaining and agree to look after it on stackage.

**Comment by cdornan** [comment]
AFAICS MissingH should have been added to lts-15.11 &mdash; it was listed in the constrints with no range restrictions &mdash; but it didn't make it through into the release.

**Comment by juhp** [comment]
It was listed already in the constraints.yaml

**Comment by juhp** [comment]
https://www.stackage.org/lts-15.13/package/MissingH-1.4.3.0
