### ISSUE TITLE
Where are the latest resolvers?

### ISSUE THREAD

**Issue by alephu5** [commercialhaskell/lts-haskell#281]
On the stackage home page I can see resolvers 15.0-15.8 but the latest version here is 14.27. Are these build plans still being checked into a public repository somewhere? [Staversion](https://hackage.haskell.org/package/staversion) isn't working with 15.x resolvers because of this.

**Comment by qrilka** [comment]
See e.g. #272

**Comment by qrilka** [comment]
@snoyberg probably it's worth to add a deprecation notice to remove confusions like this?
