### ISSUE TITLE
please add packages of relational-record about HDBC to LTS-15

### ISSUE THREAD

**Issue by khibino** [commercialhaskell/lts-haskell#282]
Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

---

version constraint for time-1.9.3 is resolved in
http://hackage.haskell.org/package/HDBC-2.4.0.3

cf. https://github.com/commercialhaskell/stackage/pull/5312 https://github.com/commercialhaskell/stackage/pull/5312/files

**Comment by bergmark** [comment]
Hmm maybe something went wrong when I added these... they didn't end up in the snapshot :-/

**Comment by alexeyzab** [comment]
Added in LTS 15.10: https://www.stackage.org/lts-15.10, thanks!
