### ISSUE TITLE
Add with-utf8-1.0.1.0

### ISSUE THREAD

**Issue by kirelagin** [commercialhaskell/lts-haskell#288]
I tested with the resolvers listed in the title. I don’t know if all of them are being actively maintained, so, please, add to as many of them as convenient for you. 

-------

Checklist for adding a package:
- [x] specified the Stackage LTS version in the summary
- [x] On your own machine, in a new directory, you have successfully run the following set of commands (replace `$package` with the name of the package that is submitted, `$version` with the version of the package you want to get into the LTS series, and `$lts` with the desired LTS series):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-$lts
      stack build --haddock --test --bench --no-run-benchmarks
- [ ] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by juhp** [comment]
We should probably change our template since we are basically only able to update the latest lts version these days, due to both people and machine resource limits.

**Comment by juhp** [comment]
Realistically we are only updating the latest major lts version these days.

**Comment by kirelagin** [comment]
That’s sad to hear, but understandable.

The primary document that needs updating is [MAINTAINERS.md](https://github.com/commercialhaskell/stackage/blob/master/MAINTAINERS.md#adding-a-package-to-an-lts-snapshot) as that is what most people are reading.

**Comment by juhp** [comment]
Thank you, good point: I updated with 9fdbe16.

**Comment by juhp** [comment]
Apologies, somehow I missed adding this package to lts-15.13 :frowning_face: 
It should get into the next minor release if all goes well.

**Comment by bergmark** [comment]
It's in lts 16.
