### ISSUE TITLE
Add JuicyPixels-blurhash-0.1.0.3 to LTS

### ISSUE THREAD

**Issue by SamProtas** [commercialhaskell/lts-haskell#290]
Checklist for adding a package:

- [x] On your machine, in a new directory, you have successfully run the following set of commands:

      stack unpack JuicyPixels-blurhash-0.1.0.3
      cd JuicyPixels-blurhash-0.1.0.3
      stack init --resolver lts-15.14
      stack --resolver lts-15.14 build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack.

This is already present in nightly

https://www.stackage.org/nightly-2020-05-26/package/JuicyPixels-blurhash-0.1.0.3

**Comment by bergmark** [comment]
It's in lts 16.
