### ISSUE TITLE
Please add a bunch of packages to the next (or current LTS)

### ISSUE THREAD

**Issue by emilypi** [commercialhaskell/lts-haskell#291]
Packages are: 

- `smash`
- `smash-aeson`
- `smash-lens`
- `smash-microlens`
- `base16`
- `base16-lens`
- `base32`
- `base32-lens`
- `nonempty-vector`
- `lens-process`

Checklist for adding a package:

- [x] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by emilypi** [comment]
@juhp You're most active so i'm pinging 😄

**Comment by bergmark** [comment]
Looks like these made it into lts 16!
