### ISSUE TITLE
Add byte-count-reader-0.10.0.1 to LTS

### ISSUE THREAD

**Issue by danielrolls** [commercialhaskell/lts-haskell#292]
Checklist for adding a package:

- [x] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

Already present in the nightly here:
https://www.stackage.org/nightly-2020-06-01/package/byte-count-reader-0.10.0.1

**Comment by bergmark** [comment]
It's in lts 16.
