### ISSUE TITLE
LTS 16.1 constraints

### ISSUE THREAD

**Issue by bergmark** [commercialhaskell/lts-haskell#293]
Added upper bounds to hasql & postgresql-binary due to:

base-prelude-1.3 ([changelog](http://hackage.haskell.org/package/base-prelude-1.3/changelog)) (Nikita Volkov <nikita.y.volkov@mail.ru> @nikita-volkov) is out of bounds for:
- hasql-1.4.4 (>=1.4 && < 2). Nikita Volkov <nikita.y.volkov@mail.ru> @nikita-volkov. @nikita-volkov. Used by: library
-  postgresql-binary-0.12.3 (>=1.4 && < 2). Nikita Volkov <nikita.y.volkov@mail.ru> @nikita-volkov. @nikita-volkov. Used by: library

And an upper bound on miniutter due to:

minimorph-0.2.2.0 ([changelog](http://hackage.haskell.org/package/minimorph-0.2.2.0/changelog)) (Mikolaj Konarski <mikolaj.konarski@funktory.com> @Mikolaj) is out of bounds for:
- miniutter-0.5.1.1 (>=0.3.0.0 && < 1). Mikolaj Konarski <mikolaj.konarski@funktory.com> @Mikolaj. @Mikolaj. Used by: library

@dfithian the oauthenticated tests started failing (due to external dependencies?), I added them to expected failures:
```
Test suite failure for package oauthenticated-0.2.1.0
    spec:  exited with: ExitFailure 1
    signing
      authorizes a request FAILED [1]
      authorizes many requests FAILED [2]
      generates a unique nonce for each repeated request

    Failures:

      test/SigningSpec.hs:21:5:
      1) signing authorizes a request
           expected: Status {statusCode = 200, statusMessage = "OK"}
            but got: Status {statusCode = 401, statusMessage = "Unauthorized"}

      To rerun use: --match "/signing/authorizes a request/"

      test/SigningSpec.hs:31:17:
      2) signing authorizes many requests
           expected: Status {statusCode = 200, statusMessage = "OK"}
            but got: Status {statusCode = 401, statusMessage = "Unauthorized"}

      To rerun use: --match "/signing/authorizes many requests/"

    Randomized with seed 314799671

    Finished in 1.8838 seconds
    3 examples, 2 failures
```

**Comment by Mikolaj** [comment]
Hi! minimorph-0.3.0.0 is available on Hackage and should not be blocked by anything, so I think the block on miniutter-0.5.1.1 can be lifted (no idea how to check if it is).

**Comment by Mikolaj** [comment]
Oh, I see 0.3.0.0 is major version bump. Fair enough. Let it be and keep up the good work!

**Comment by dfithian** [comment]
Huh, I bumped the LTS to 16.1 and ran the tests. They succeeded for me:

```bash
signing
  authorizes a request
  authorizes many requests
  generates a unique nonce for each repeated request

Finished in 3.5666 seconds
3 examples, 0 failures

oauthenticated> Test suite spec passed
Completed 4 action(s).
```

All I had to do was remove a redundant Data.Monoid import in a few places. So perhaps it was a blip? This does have an external dependency on `https://postman-echo.com/oauth1`.

**Comment by nikita-volkov** [comment]
"base-prelude" 1.4 has been released. Why are we restricted to 1.3?

**Comment by bergmark** [comment]
@nikita-volkov by default we don't include breaking changes within an LTS major version, https://github.com/commercialhaskell/lts-haskell#how-it-works

**Comment by nikita-volkov** [comment]
@bergmark Thanks for the explanation!
