### ISSUE TITLE
Add ftp-client-0.5.* and ftp-client-conduit-0.5.* to lts 16

### ISSUE THREAD

**Issue by DanBurton** [commercialhaskell/lts-haskell#294]
Checklist for adding a package:

- [x] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks

      # tested with ftp-client-0.5.1.4, ftp-client-conduit-0.5.0.5

- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by alexeyzab** [comment]
Added in lts-16.2: https://www.stackage.org/lts-16.2/package/ftp-client-0.5.1.4, https://www.stackage.org/lts-16.2/package/ftp-client-conduit-0.5.0.5
