### ISSUE TITLE
LTS 16.2 constraints

### ISSUE THREAD

**Issue by alexeyzab** [commercialhaskell/lts-haskell#295]
Added an upper bound for `dhall-bash` due to:

dhall-1.32.0 ([changelog](http://hackage.haskell.org/package/dhall-1.32.0/changelog)) (Gabriel Gonzalez <Gabriel439@gmail.com> @Gabriel439) is out of bounds for:
- [ ] dhall-bash-1.0.31 (>=1.33.0 && < 1.34). Gabriel Gonzalez <Gabriel439@gmail.com> @Gabriel439. @dhall-lang. Used by: library

Added an upper bound for `foldl` due to:

foldl-1.4.7 ([changelog](http://hackage.haskell.org/package/foldl-1.4.7/changelog)) (Gabriel Gonzalez <Gabriel439@gmail.com> @Gabriel439) is out of bounds for:
- [ ] stackcollapse-ghc-0.0.1 (==1.4.6). Marcin Rzeźnicki <marcin.rzeznicki@gmail.com> @marcin-rzeznicki. @marcin-rzeznicki. Used by: executable

Added an upper bound for `unordered-containers` due to:

unordered-containers-0.2.11.0 ([changelog](http://hackage.haskell.org/package/unordered-containers-0.2.11.0/changelog)) (Grandfathered dependencies) is out of bounds for:
- [ ] req-3.2.0 (>=0.2.5 && < 0.2.11). Mark Karpov <markkarpov92@gmail.com> @mrkkrp. @mrkkrp. Used by: test-suite

**Comment by Gabriel439** [comment]
@alexeyzab: This doesn't explain why `dhall` isn't upgraded to the latest version (1.33.0), which would satisfy the `dhall-bash` version bounds

**Comment by Gabriel439** [comment]
Never mind, I just saw https://github.com/commercialhaskell/stackage/issues/5465

**Comment by marcin-rzeznicki** [comment]
I just released 0.0.1.1 version of `stackcollapse-ghc` with some fixes. Therein included an upgraded upper bound on `foldl` to accommodate `1.4.7`. Thanks for reporting
