### ISSUE TITLE
add string-interpolate

### ISSUE THREAD

**Issue by williamyaoh** [commercialhaskell/lts-haskell#296]
Checklist for adding a package:

- [x] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts-16.3
      stack --resolver lts-16.3 build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by juhp** [comment]
AFAICT string-interpolate is already in Stackage LTS

https://www.stackage.org/package/string-interpolate/snapshots

**Comment by williamyaoh** [comment]
Ah, my mistake, I should have been more specific in the title; I was
specifically looking to upgrade to 0.3.0.0 in lts-16.

2020年7月12日(日) 3:56 Jens Petersen <notifications@github.com>:
