### ISSUE TITLE
Add matrix-as-xyz

### ISSUE THREAD

**Issue by narumij** [commercialhaskell/lts-haskell#297]
Checklist for adding a package:

- [x] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by snoyberg** [comment]
Added in LTS 16.7: https://www.stackage.org/lts-16.7/package/matrix-as-xyz-0.1.1.3
