### ISSUE TITLE
YAML definitions for lts-15/lts-16 are missing

### ISSUE THREAD

**Issue by sol** [commercialhaskell/lts-haskell#299]
This repository does not contain YAML definitions for `lts-15`/`lts-16`.  This causes versions of `stack < 2` to fail (I tested `1.9.1` and `1.9.3`).

Is it possible to add them?  Are there any workarounds?

The project I'm dealing with relies on `stack image`; I'm not sure if upgrading `stack` is feasible right now.

**Comment by qrilka** [comment]
Legacy snapshots were discontinued - https://www.stackage.org/blog/2020/02/discontinuing-legacy-snapshots

**Comment by qrilka** [comment]
In principle Stackage curator tool still has a command to produce a legacy snapshot - https://github.com/commercialhaskell/curator/blob/master/app/curator.hs#L57 but without digging into it I don't remember what inputs does it need.

**Comment by DanBurton** [comment]
If you are stuck with an old `stack`, I'd recommend sticking to older snapshots.

I'm not sure what the stack-2 equivalent of `stack image` is.

**Comment by DanBurton** [comment]
For alternative approaches to `stack image`, see: https://www.fpcomplete.com/blog/2017/12/building-haskell-apps-with-docker/
