### ISSUE TITLE
Add BNFC to LTS

### ISSUE THREAD

**Issue by andreasabel** [commercialhaskell/lts-haskell#300]
BNFC-2.8.4 is on nightly, I would like to have it added to LTS.
(N.B.: BNFC is mostly an executable and does not strictly follow the package version policy.)

Checklist for adding a package:

- [X] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks
- [X] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by mihaimaruseac** [comment]
Added to [LTS-16.23](https://www.stackage.org/lts-16.23)

**Comment by andreasabel** [comment]
Great, thanks!
