### ISSUE TITLE
Missing Docker image for lts-17.0

### ISSUE THREAD

**Issue by AshleyYakeley** [commercialhaskell/lts-haskell#310]
`fpco/stack-build:lts-17.0` not found on DockerHub.

**Comment by mihaimaruseac** [comment]
https://hub.docker.com/r/commercialhaskell/stackage/tags?page=1&ordering=last_updated

**Comment by AshleyYakeley** [comment]
Pulled, thanks.

Is the plan to have one image per major LTS, rather than one per minor release?

**Comment by mihaimaruseac** [comment]
Yes. There's no need to have an image for every minor release as we don't change the base image that often.

**Comment by AshleyYakeley** [comment]
That makes sense. Thanks!
