### ISSUE TITLE
Add back cabal-appimage

### ISSUE THREAD

**Issue by gbrsales** [commercialhaskell/lts-haskell#311]
Could you please add back `cabal-appimage` to LTS 17?

It was removed because of an incompatible upper bound with GHC 8.10.3, now fixed with https://github.com/commercialhaskell/stackage/pull/5856.

**Comment by jkachmar** [comment]
This should be resolved in LTS-17.5; it's currently building and I'll try to remember to update this issue after that's finishes and it's been published.

**Comment by jkachmar** [comment]
[Present in LTS-17.5](https://www.stackage.org/lts-17.5/package/cabal-appimage-0.3.0.2)
