### ISSUE TITLE
Reenable Agda in LTS

### ISSUE THREAD

**Issue by andreasabel** [commercialhaskell/lts-haskell#312]
Agda-2.6.1.3 is in nightly now; please add to LTS (ghc 8.10.3).

Checklist for adding a package:

- [x] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by jkachmar** [comment]
This should be resolved in LTS-17.5; it's currently building and I'll try to remember to update this issue after that's finishes and it's been published.

**Comment by jkachmar** [comment]
[Present in LTS-17.5](https://www.stackage.org/lts-17.5/package/Agda-2.6.1.3)

**Comment by andreasabel** [comment]
Fantastic!!
