### ISSUE TITLE
Reenable haskell-src in lts

### ISSUE THREAD

**Issue by andreasabel** [commercialhaskell/lts-haskell#313]
Please add [haskell-src](https://www.stackage.org/package/haskell-src) to LTS again.

Checklist for adding a package:

- [x] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by jkachmar** [comment]
This should be resolved in LTS-17.5; it's currently building and I'll try to remember to update this issue after that's finishes and it's been published.

**Comment by jkachmar** [comment]
[Present in LTS-17.5](https://www.stackage.org/lts-17.5/package/HTF-0.14.0.6)

**Comment by andreasabel** [comment]
Excellent!
