### ISSUE TITLE
enable pandoc in lts-17

### ISSUE THREAD

**Issue by juhp** [commercialhaskell/lts-haskell#314]
I believe it should build okay from my local testing.
But I can verify this soon: I think it needs a few additional deps too.

**Comment by jkachmar** [comment]
This should be resolved in LTS-17.5; it's currently building and I'll try to remember to update this issue after that's finishes and it's been published.

**Comment by jkachmar** [comment]
[Present in LTS-17.5](https://www.stackage.org/lts-17.5/package/pandoc-2.11.4)
