### ISSUE TITLE
Re-add `servant-auth-*` packages

### ISSUE THREAD

**Issue by jkachmar** [commercialhaskell/lts-haskell#317]
Per [this comment](https://github.com/haskell-servant/servant-auth/pull/185#issuecomment-794659288) it looks like the `servant-auth-*` packages should be good to add back to LTS-17. They were originally [disabled due to a lack of GHC 8.10 support](https://github.com/commercialhaskell/stackage/blob/a7ef53f5e96b74e858390e3e51ccb70e12728c6b/build-constraints.yaml#L4052-L4057) but that's since been cleared up.

@mihaimaruseac has been working on getting the nightly moved over to 9.0.1, which `servant-auth` (and co.) don't currently support so I don't think we'll be able to turn these back on for the nightly builds yet.

**Comment by juhp** [comment]
Looks like they were already added to lts17 so closing.

eg see latest https://www.stackage.org/lts-17.9
