### ISSUE TITLE
Add vcs-ignore

### ISSUE THREAD

**Issue by vaclavsvejcar** [commercialhaskell/lts-haskell#319]
Checklist for adding a package:

- [x] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

The [vcs-ignore](https://github.com/vaclavsvejcar/vcs-ignore) library is [already in Nightly](https://www.stackage.org/nightly-2021-05-28/package/vcs-ignore-0.0.1.0), can we please have it in next _LTS_?

**Comment by mihaimaruseac** [comment]
It si in [LTS 18.0](https://www.stackage.org/lts-18.0)
