### ISSUE TITLE
add rpm-nvr

### ISSUE THREAD

**Issue by juhp** [commercialhaskell/lts-haskell#320]
Checklist for adding a package:
- [x] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):
      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack.

**Comment by alexeyzab** [comment]
Added in 18.3: https://www.stackage.org/lts-18.3/package/rpm-nvr-0.1.0
