### ISSUE TITLE
Add lzma-clib

### ISSUE THREAD

**Issue by Bodigrim** [commercialhaskell/lts-haskell#321]
Checklist for adding a package:

- [x] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

See https://github.com/commercialhaskell/stackage/pull/6106 for motivation. While `lzma` package has been present in LTS for ages, it is actually broken and unbuildable on Windows, because C sources are not bundled and must be obtained separately from `lzma-clib`, which is missing from LTS.

**Comment by Bodigrim** [comment]
@juhp is it a right repository? Sorry, never did it before.

**Comment by juhp** [comment]
Yes!

**Comment by cdornan** [comment]
Added to [lts-18.4](https://www.stackage.org/lts-18.4)
