### ISSUE TITLE
[add] cabal-clean, java-adt, Sit

### ISSUE THREAD

**Issue by andreasabel** [commercialhaskell/lts-haskell#326]
Please add these packages to LTS:
- cabal-clean (https://github.com/commercialhaskell/stackage/pull/6169)
- java-adt
- Sit

Checklist for adding a package:

- [x] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by snoyberg** [comment]
All three added:

* https://www.stackage.org/lts-18.6/package/cabal-clean-0.1.20210815
* https://www.stackage.org/lts-18.6/package/Sit-0.2021.1.18
* https://www.stackage.org/lts-18.6/package/java-adt-0.2018.11.4
