### ISSUE TITLE
Renable `json`, add `hasktags` to LTS

### ISSUE THREAD

**Issue by andreasabel** [commercialhaskell/lts-haskell#327]
Renable `json`, add `hasktags` to LTS.

I successfully ran
```
stack build --test --bench --haddock --resolver lts-18.8 --system-ghc json hasktags
```
on stack version 2.7.3.

**Comment by alexeyzab** [comment]
Added in LTS-18.10: [json](https://www.stackage.org/lts-18.10/package/json-0.10), [hasktags](https://www.stackage.org/lts-18.10/package/hasktags-0.72.0).
