### ISSUE TITLE
Add tmp-proc-0.5.0.1 and hspec-tmp-proc-0.5.0.1

### ISSUE THREAD

**Issue by adetokunbo** [commercialhaskell/lts-haskell#332]
Checklist for adding a package:

- [x] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      N.B. I modified this to check both packages as shown below*
      # stack unpack $package-$version
      # cd $package-$version
      mkdir stack-unpack
      cd stack-unpack
      stack unpack tmp-proc-0.5.0.1
      stack unpack hspec-tmp-proc-0.5.0.1
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks

- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by juhp** [comment]
https://www.stackage.org/lts-18.23/package/hspec-tmp-proc-0.5.0.1
