### ISSUE TITLE
Reenable MissingH in LTS

### ISSUE THREAD

**Issue by andreasabel** [commercialhaskell/lts-haskell#334]
MissingH is in LTS 17, but not 18.

The `errorcall-eq-instance` (see #280) is only depended on by the testsuite for GHC < 7.8.  This should not be relevant for the new LTS.

Checklist for adding a package:

- [x] On your machine, in a new directory, you have successfully run the following set of commands:

      stack unpack MissingH-1.5.0.0
      cd MissingH-1.5.0.0
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks

- [x] You're using the latest version of Stack.

**Comment by bergmark** [comment]
https://www.stackage.org/lts-18.26
