### ISSUE TITLE
lts-19.0 notes

### ISSUE THREAD

**Issue by juhp** [commercialhaskell/lts-haskell#337]
The issue records the manual changes that were made in order to get the initial lts-19.0 snapshot release out:

- disabled Sit: see #336
- allowed lapack testsuite to fail (@thielema)
- allowed cryptostore testsuite to fail (@ocheron)

This mostly just FYI - I believe these are still currently enabled in latest Stackage Nightly.

**Comment by ocheron** [comment]
Bug should be resolved in cryptostore-0.2.2.0.
