### ISSUE TITLE
Re-add aeson-diff to LTS

### ISSUE THREAD

**Issue by ysangkok** [commercialhaskell/lts-haskell#338]
Checklist for adding a package:

- [X] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack aeson-diff-1.1.0.12
      cd aeson-diff-1.1.0.12
      stack init --resolver lts # I skip this because there is already a stack.yaml, so I adjust it instead
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks
- [X] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by bergmark** [comment]
Done
