### ISSUE TITLE
Re-enable conduit-algorithms

### ISSUE THREAD

**Issue by luispedro** [commercialhaskell/lts-haskell#339]
Latest version is GHC9-compatible (https://hackage.haskell.org/package/conduit-algorithms-0.0.12.0 released Mar 19). It is part of `nightly` as well.

Checklist for adding a package:

- [x] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by bergmark** [comment]
Done
