### ISSUE TITLE
Re-enable Freckle packages

### ISSUE THREAD

**Issue by pbrisbin** [commercialhaskell/lts-haskell#340]
The following Freckle packages were dropped before lts-19 as part of the aeson-2.0 break, but are back in nightly now and compile fine against lts-19 in all our projects via `extra-deps`.

Can they be added in the next lts-19?

- aws-xray-client-0.1.0.2
- aws-xray-client-persistent-0.1.0.5
- aws-xray-client-wai-0.1.0.2
- freckle-app-1.0.2.10

They may have some transitive dependencies in the same state, which I assume can be easy for you to find and possible to bring back as well.

Apologies if this isn't the right process or I've omitted some necessary details, please let me know.

**Comment by bergmark** [comment]
These need to be resolved to be compatible with LTS 19:

```
base-4.15.1.0 ([changelog](http://hackage.haskell.org/package/base-4.15.1.0/changelog)) is out of bounds for:
- [ ] ekg-core-0.1.1.7 (>=4.6 && < 4.15). Eric Conlon <ejconlon@gmail.com> @ejconlon, Library and exe bounds failures. @tibbe. Used by: library


ghc-prim-0.7.0 ([changelog](http://hackage.haskell.org/package/ghc-prim-0.7.0/changelog)) is out of bounds for:
- [ ] ekg-core-0.1.1.7 (< 0.7). Eric Conlon <ejconlon@gmail.com> @ejconlon, Library and exe bounds failures. @tibbe. Used by: library


hspec-junit-formatter-1.0.3.0 ([changelog](http://hackage.haskell.org/package/hspec-junit-formatter-1.0.3.0/changelog)) (Freckle Engineering <freckle-engineering@renaissance.com> @pbrisbin @mjgpy3 @stevenxl) is out of bounds for:
- [ ] freckle-app-1.0.2.10 (>=1.1.0.1). Freckle Engineering <freckle-engineering@renaissance.com> @pbrisbin @mjgpy3 @stevenxl, Library and exe bounds failures. @freckle. Used by: library
```

**Comment by bergmark** [comment]
the aws packages have been added.

**Comment by pbrisbin** [comment]
Oh, sorry. I forgot about `ekg-core`. The bounds just need a bump, but the maintainers are unresponsive :frowning_face: 

`hspec-junit-formatter` is more interesting, and I actually don't know how to resolve...

`lts-19` should've gotten `hspec-junit-formatter` `1.1` (the latest). It was pinned because of older `freckle-app`'s bounds in `lts-18`. We couldn't update `hspec-junit-formatter` because we couldn't update `freckle-app` because we lost `ekg-core`. Later, `freckle-app` was disabled entirely due to `aeson` `2.0`. It was all supposed to get resolved together in the next LTS.

Is it too late now to update `lts-19` to `hspec-junit-formatter` `1.1`?

**Comment by andreasabel** [comment]
@pbrisbin : Concerning `ekg-core`, I [revised it](https://hackage.haskell.org/package/ekg-core-0.1.1.7/revisions/) on Hackage, so maybe it can be reenabled in Stackage (nightly and LTS).

**Comment by pbrisbin** [comment]
@andreasabel Thanks!

@bergmark I think we can close this issue and I can open a new one to discuss `hspec-junit-formatter`?
