### ISSUE TITLE
Add: brotli brotli-streams xor http-io-streams hackage-cli

### ISSUE THREAD

**Issue by andreasabel** [commercialhaskell/lts-haskell#342]
Following their addition to nighlty, I'd like to add these packages to LTS.
- https://github.com/commercialhaskell/stackage/pull/6559

- [x] On your machine, in a new directory, you have successfully run the following set of commands...
  I ran:
  ```
  stack --resolver lts build brotli brotli-streams xor http-io-streams hackage-cli --test --bench
  ```
- [x] You're using the latest version of Stack.

**Comment by bergmark** [comment]
Done in https://www.stackage.org/lts-19.8
