### ISSUE TITLE
Re-enable minio-hs

### ISSUE THREAD

**Issue by donatello** [commercialhaskell/lts-haskell#344]
New release has been made that works with GHC 9.0.2. Please enable it for LTS 19.x. 

Checklist for adding a package:

- [x] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by donatello** [comment]
I just want to add that the latest minio-hs release does not yet build with GHC 9.2 (using cabal) because of a dependency on relude, which is not yet compatible with GHC 9.2. However it (somehow) does build with stack (on lts-19.x) and GHC 9.2 as can be seen [here](https://github.com/minio/minio-hs/runs/6633024928?check_suite_focus=true).

**Comment by alexeyzab** [comment]
Seems like `minio-hs` is [already present in last week's LTS](https://www.stackage.org/lts-19.11/package/minio-hs-1.6.0), so I'll close this issue.
