### ISSUE TITLE
Upgrade `github` from 0.27 to latest (0.28.0.1)

### ISSUE THREAD

**Issue by andreasabel** [commercialhaskell/lts-haskell#347]
Is there a reason that `github` isn't in its latest version in LTS?
Otherwise, you can upgrade

- [x] `stack --resolver lts build --haddock --test --bench --no-run-benchmarks`
- [x] You're using the latest version of Stack.

**Comment by cdornan** [comment]
LTS is cut from nightly, thereafter non breaking version updates (according to the PVP) &dash; LTS-20 should contain 0.28.*  (already on nightly).

**Comment by andreasabel** [comment]
Thanks for the explanation!
