### ISSUE TITLE
Please add pasta-curves 0.0.0.0 to LTS

### ISSUE THREAD

**Issue by eschorn1** [commercialhaskell/lts-haskell#348]
Checklist for adding a package:

- [x] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

Thank you!!

**Comment by juhp** [comment]
This was actually added week as https://www.stackage.org/lts-19.21/package/pasta-curves-0.0.0.0
