### ISSUE TITLE
Add co-log-core and lsp

### ISSUE THREAD

**Issue by Bodigrim** [commercialhaskell/lts-haskell#349]
Cf. https://github.com/commercialhaskell/stackage/pull/6784

Checklist for adding a package:

- [x] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by Bodigrim** [comment]
@alexeyzab @juhp just a gentle ping.

**Comment by cdornan** [comment]
@Bodigrim sorry, i have only just seen this (we put out the LTS teleases on weekends; I am on this week).

This is the repo for LTS but you clearly want to add hie-bios to the (main) nightly release (it will automatically feed into the next LTS we cut, but we can manually add it to LTS, but usually only after it has been established on nightly.)

Long story short, I will add hie-bios to nightly which should appear on Monday, or maybe Tuesday.

**Comment by Bodigrim** [comment]
My ultimate goal is to have `lsp` in LTS 20, this is a fairly important package.

I thought that `hie-bios` got into Nightly after https://github.com/commercialhaskell/stackage/pull/6784, but probably I have not cleared all `hie-bios < 0`?.. Sorry for extra hassle.

**Comment by juhp** [comment]
(hie-bios is already in lts-20 afaict btw)

https://www.stackage.org/lts-20.4/package/hie-bios-0.9.1

**Comment by Bodigrim** [comment]
Now that `lsp` hit the nightly snapshot, could it be re-enabled in LTS please?

**Comment by juhp** [comment]
(still working on it btw...)
