### ISSUE TITLE
Add `text-regex-replace` to LTS 20

### ISSUE THREAD

**Issue by prikhi** [commercialhaskell/lts-haskell#350]
Was in LTS 19, fell out of 20, brought it back into nightly: https://github.com/commercialhaskell/stackage/pull/6783

Checklist for adding a package:

- [x] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks
- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by alexeyzab** [comment]
Added in [LTS-20.3](https://www.stackage.org/lts-20.3/package/text-regex-replace-0.1.1.5)
