### ISSUE TITLE
Could we add the following six packages to the lts-19 series?  glib-0.13.8.2, cairo-0.13.8.2, pango-0.13.8.2, statestack-0.3.1, diagrams-cairo-1.4.2, LPFP-1.0

### ISSUE THREAD

**Issue by walck** [commercialhaskell/lts-haskell#352]
Checklist for adding a package:

- [ ] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts
      @
- [ ] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by juhp** [comment]
Unfortunately we aren't updating lts-19 anymore: we only have resources for one current LTS.

Do you need any of those packages to be added to lts-20?

**Comment by walck** [comment]
Ok.  I submitted a separate request for the packages I would like to add to lts-20.
