### ISSUE TITLE
add LPFP-1.0 to lts-20

### ISSUE THREAD

**Issue by walck** [commercialhaskell/lts-haskell#353]
Checklist for adding a package:

- [ ] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks
- [ ] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by walck** [comment]
Actually, could I add a 4th package to the list?  learn-physics-0.6.5

**Comment by alexeyzab** [comment]
Hi there! I've tried adding these packages over the weekend but encountered the following problems:

When adding `spatial-math`:

```
TypeCompose (Compilation failures, Scott N. Walck <walck@lvc.edu> @walck) (not present) depended on by:
- [ ] spatial-math-0.5.0.1 (>=0.9.11). Library and exe bounds failures, Scott N. Walck <walck@lvc.edu> @walck. Used by: library
```

Then I tried adding `TypeCompose` just to try, but alas:

```
base-4.16.4.0 ([changelog](http://hackage.haskell.org/package/base-4.16.4.0/changelog)) is out of bounds for:
- [ ] TypeCompose-0.9.14 (>=4.9 && < 4.16). Scott N. Walck <walck@lvc.edu> @walck. Used by: library
```

And without `spatial-math` I've run into these:

```
spatial-math (Library and exe bounds failures, Scott N. Walck <walck@lvc.edu> @walck) (not present) depended on by:
- [ ] LPFP-1.0 (-any). Scott N. Walck <walck@lvc.edu> @walck. Used by: library
- [ ] not-gloss-0.7.7.0 (>=0.2.1.2). Library and exe bounds failures, Scott N. Walck <walck@lvc.edu> @walck. Used by: library
```

**Comment by walck** [comment]
The trouble is that I asked for spatial-math-0.2.7.0.  The most  recent version of spatial-math that is on hackage requires TypeCompose.  The author of TypeCompose is trying to deprecate it, as its functionality is available in better places now.  I have tried to contact the maintainer of spatial-math several times over the past few months, but I have not gotten any response.  Another person has submitted a pull request on github, removing the dependency of spatial-math on TypeCompose, but that pull request languishes.  spatial-math-0.2.7.0 is the last version that does not require TypeCompose.  spatial-math-0.2.7.0 is sufficient to enable recent versions of not-gloss, learn-physics, and LPFP to build.  The stackage nightly repo has put in an upper bound of 0.3 on spatial-math so that these latter packages can build.  Are you willing to try to add spatial-math-0.2.7.0 to the LTS 20 series?  Perhaps you have other advice for me on how to handle this.  Thanks.

**Comment by mihaimaruseac** [comment]
LPFP is not yet in nightly, we need that one first.

**Comment by mihaimaruseac** [comment]
The other 3 packages with the given bounds don't have bounds issues. If they build, the next LTS will contain them

**Comment by mihaimaruseac** [comment]
Only LPFP left to add, once it gets into nightly

**Comment by juhp** [comment]
Correct me if I am wrong, but I don't think Nightly is a hard requirement for adding a package to lts.

**Comment by mihaimaruseac** [comment]
All packages added to [LTS 20.20](https://www.stackage.org/lts-20.20)
