### ISSUE TITLE
Please create LTS 21 for ghc-9.4

### ISSUE THREAD

**Issue by neilmayhew** [commercialhaskell/lts-haskell#355]
I understand that this is dependent on Nightly being able to switch to ghc-9.6. I've been trying out 9.6 with some of my projects and I haven't had any problems with it.

I'd really like to be able to start using 9.4 for my production projects.

**Comment by alaendle** [comment]
Just out of curiosity, any specific reason to switch to 9.4? From my point of view 9.6 might track more attention, but I haven't found relevant differences - at least for my projects - from 9.2 to 9.4. Nonetheless you are right, maybe time has come to switch to newer GHC releases. But also we don't have to rush into anything - release 9.4 might be quite stable, but I'm unsure if we should build upon the first 9.6 release. So there is no harm in waiting 😉 and surely the inevitable will happen...

**Comment by juhp** [comment]
Yeah I think we need to think about the timing carefully - though nominally 9.2 is also considered an LTS release of ghc.

**Comment by andreasabel** [comment]
I think GHC 9.4 has been out long enough to deserve a LTS.

@neilmayhew wrote:
> I understand that this is dependent on Nightly being able to switch to ghc-9.6.

Is it? I don't think so.  At least this wasn't the case.  I think the only requirement is that GHC has advanced to a .2 minor version, e.g. 9.4.2 (rather than 9.4.1 which is considered experimental).

@alaendle wrote:
> Just out of curiosity, any specific reason to switch to 9.4? 

Yes, GHC 9.4 rebuilds your project faster than 9.2 because it has a better recompilation checker.

**Comment by andreasabel** [comment]
Btw, over Easter I produced a chart displaying packages and their "age" (in terms of when they first entered a LTS) for the latest LTSs per GHC version.

![chart](https://user-images.githubusercontent.com/1155218/231845875-d347a077-4dab-49d9-9835-d018f04bc39c.svg)

The last column is a recent `nightly` (GHC 9.4).  It is significantly lower than the column for LTS 20.x (GHC 9.2).  This shows that many packages have not been updated to GHC 9.4 or dependencies admitted to `nightly`.
Could we have a draft for a LTS 21, pinging maintainers whose packages could be missing in LTS 21 over LTS 20?

**Comment by ysangkok** [comment]
The latest Stack ([Hackage](https://hackage.haskell.org/package/stack)) is v2.9.3, which was released before [Stack became able to install GHC 9.4 on Debian 11](https://github.com/commercialhaskell/stack/pull/5987). Given that Debian 11 is popular, I think it would be best to wait with the next LTS until a new version of Stack has been released.

**Comment by andreasabel** [comment]
@mpilgrem Is there a schedule for the next release of Stack yet?  (Couldn't find a milestone for it: https://github.com/commercialhaskell/stack/milestones)

**Comment by mpilgrem** [comment]
I'll start the process to release a new Stack, then.

**Comment by bergmark** [comment]
> Btw, over Easter I produced a chart displaying packages and their "age" (in terms of when they first entered a LTS) for the latest LTSs per GHC version.

I think I missed replying to your e-mail about this, but: Big thanks for making this!

> The last column is a recent nightly (GHC 9.4). It is significantly lower than the column for LTS 20.x (GHC 9.2). This shows that many packages have not been updated to GHC 9.4 or dependencies admitted to nightly.

This could be part of it, but I suspect that a big reason is that we have not been as active in enabling packages that have been updated on the stackage side. I will run the commenter flow for the next nightly and we'll see how much of a difference it makes.

**Comment by bergmark** [comment]
Looks like I was wrong 😬 we have been keeping up, so there were not that many packages that could be re-enabled.

**Comment by andreasabel** [comment]
> The latest Stack ([Hackage](https://hackage.haskell.org/package/stack)) is v2.9.3, which was released before [Stack became able to install GHC 9.4 on Debian 11](https://github.com/commercialhaskell/stack/pull/5987). Given that Debian 11 is popular, I think it would be best to wait with the next LTS until a new version of Stack has been released.

Stack 2.11.1 is out, for a short while already.  Any other blockers?

**Comment by andreasabel** [comment]
Looks like everyone is busy...  But maybe it would be good to put up some issue that lists the TODOs for LTS 21 and tracks progress.  This would make it more transparent on which issues this project is stuck, and maybe attract some help.

**Comment by juhp** [comment]
I agree I think we should start working on this.

**Comment by juhp** [comment]
This is the current diff between lts-20 and nightly:

https://www.stackage.org/diff/lts-20.25/nightly-2023-06-16

**Comment by alaendle** [comment]
> This is the current diff between lts-20 and nightly:
> 
> https://www.stackage.org/diff/lts-20.25/nightly-2023-06-16

Looks OK to me; at some point you have to dare to make the cut. Or is there something (a package, process, etc.) we still have to wait for?

**Comment by alaendle** [comment]
LTS-21 is out https://www.stackage.org/diff/lts-20.26/lts-21.0 (and I hope for a ghc-9.6 nightly tomorrow, https://github.com/commercialhaskell/stackage/issues/6993).

**Comment by neilmayhew** [comment]
Great work, everyone! Thanks a bunch.

**Comment by andreasabel** [comment]
Here is an updated visualisation of the stackage history by GHC version. 

![chart-2023-07-03](https://github.com/commercialhaskell/lts-haskell/assets/1155218/68843ce6-d0f9-4b5d-91d5-a03593870b7a)

The last three columns are 9.2.8 (lts-20.26), 9.4.5 (lts-21.1) and 9.6.2 (nightly-2023-07-03).

**Comment by juhp** [comment]
Thanks @andreasabel - btw is the code somewhere - sounds interesting to play with :-)

So for example the bottom-most red colour is for packages that have been in Stackage since with ghc-7.8 iiuc.

**Comment by andreasabel** [comment]
@juhp: The code is a bit of a patchwork still right now, with some manual and awk data preparation step.
However, I could brush it up a bit.
Would you accept a PR against https://github.com/commercialhaskell/stackage-snapshots ?  Then it could generate the chart there via CI.

**Comment by juhp** [comment]
Interesting idea - not sure, but you can try asking there?

**Comment by andreasabel** [comment]
- https://github.com/commercialhaskell/stackage-snapshots/pull/1
