### ISSUE TITLE
Please add sandwich-hedgehog-0.1.3.0 to lts-20

### ISSUE THREAD

**Issue by thomasjm** [commercialhaskell/lts-haskell#356]
Per https://github.com/codedownio/sandwich/issues/80?notification_referrer_id=NT_kwDOABjyrrI2MTQ4ODc5Njk4OjE2MzQ5OTA#issuecomment-1508414392

Checklist for adding a package:

- [X] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks
- [X] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by mihaimaruseac** [comment]
Added to [LTS 20.20](https://www.stackage.org/lts-20.20)
