### ISSUE TITLE
add simple-prompt to lts

### ISSUE THREAD

**Issue by juhp** [commercialhaskell/lts-haskell#357]
Checklist for adding a package:

- [x] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks

**Comment by mihaimaruseac** [comment]
Added to [LTS 20.20](https://www.stackage.org/lts-20.20)
