### ISSUE TITLE
Add vector-hashtables to Stackage LTS

### ISSUE THREAD

**Issue by ulysses4ever** [commercialhaskell/lts-haskell#360]
I checked both of the below for the nightly version (`vector-hashtables-0.1.1.3`).

Checklist for adding a package:

- [x] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks

or using the [verify-package script](https://github.com/commercialhaskell/stackage/blob/master/verify-package):

      verify-package $package lts

- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by juhp** [comment]
Sorry for not getting this into lts-20.24

**Comment by ulysses4ever** [comment]
@juhp no worries and thanks for your work anyway! Is there anything we could do to make sure we'll get in the next one? Or just wait?

**Comment by juhp** [comment]
No no, just my slip - I was busy dealing with crypton and updating lts to 9.2.8 - hopefully should get into the next one 🤞

**Comment by ulysses4ever** [comment]
Awesome, thanks!

**Comment by ulysses4ever** [comment]
Thank you!
