### ISSUE TITLE
Restore vector-sized

### ISSUE THREAD

**Issue by Bodigrim** [commercialhaskell/lts-haskell#363]
Could `vector-sized` please be restored in `lts-21` series? Currently blocked on migration because of it.

Checklist for adding a package:

- [x] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks

or using the [verify-package script](https://github.com/commercialhaskell/stackage/blob/master/verify-package):

      verify-package $package lts

- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by alexeyzab** [comment]
Added in [LTS-21.3](https://www.stackage.org/lts-21.3/package/vector-sized-1.5.0)
