### ISSUE TITLE
Restore universum

### ISSUE THREAD

**Issue by gromakovsky** [commercialhaskell/lts-haskell#364]
`universum-1.8.2` works fine with packages from the latest LTS.

Checklist for adding a package:

- [x] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks

or using the [verify-package script](https://github.com/commercialhaskell/stackage/blob/master/verify-package):

      verify-package $package lts

- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

The only thing I was unable to check myself is benchmarks, because I have only M1 macbook and `gauge` doesn't build there. I'm pretty sure they should be fine though.

**Comment by alexeyzab** [comment]
Added in [LTS-21.3](https://www.stackage.org/lts-21.3/package/universum-1.8.2)
