### ISSUE TITLE
Bump LTS 21 to GHC 9.4.6

### ISSUE THREAD

**Issue by swamp-agr** [commercialhaskell/lts-haskell#366]
GHC 9.4.6 has been released: 

https://www.haskell.org/ghc/download_ghc_9_4_6.html

NB. It contains the fix of the linker issue that impacts `stack repl`and HLS usage on our codebase, I opened this issue mostly for tracking purposes.

**Comment by juhp** [comment]
https://www.stackage.org/lts-21.8 is out
