### ISSUE TITLE
add diagrams-cairo-1.4.2.1 to lts 21

### ISSUE THREAD

**Issue by walck** [commercialhaskell/lts-haskell#367]
Checklist for adding a package:

- [ ] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks

or using the [verify-package script](https://github.com/commercialhaskell/stackage/blob/master/verify-package):

      verify-package $package lts

- [ ] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by juhp** [comment]
Added in https://www.stackage.org/lts-21.14/package/diagrams-cairo-1.4.2.1

Sorry this took us so long
