### ISSUE TITLE
Please add HMock-0.5.1.2 to LTS

### ISSUE THREAD

**Issue by cdsmith** [commercialhaskell/lts-haskell#369]
Sorry, I fell behind on keeping this up to date with new GHC versions, but it's fixed now and I have run all the tests with the latest LTS.  I'd appreciate it being added to the current LTS again.

**Comment by juhp** [comment]
It was in lts-22.0 but got dropped temporarily with the new lts workflow.
Hopefully it should get added back soon.

**Comment by juhp** [comment]
https://www.stackage.org/lts-22.3/package/HMock-0.5.1.2
