### ISSUE TITLE
please add packages of relational-record about product-isomorphic to LTS-21

### ISSUE THREAD

**Issue by khibino** [commercialhaskell/lts-haskell#370]
Checklist for adding a package:

- [x] On your machine, in a new directory, you have successfully run the following set of commands (replacing $package and $version with the name and version of the package you want to add to Stackage LTS):

      stack unpack $package-$version
      cd $package-$version
      stack init --resolver lts
      stack --resolver lts build --haddock --test --bench --no-run-benchmarks

or using the [verify-package script](https://github.com/commercialhaskell/stackage/blob/master/verify-package):

      verify-package $package lts

- [x] You're using the latest version of Stack. (Otherwise please try running `stack upgrade` and re-running your commands. If that fails, please include the output of `stack --version` in this issue.)

**Comment by khibino** [comment]
product-isomorphic-0.0.3.4 passed check of `stack --resolver lts build ...` against LTS-21.23

-----

dependency chain list:

- [ ] product-isomorphic
- [ ] persistable-record
- [ ] relational-query
- [ ] relational-schemas
- [ ] relational-query-HDBC
- [ ] persistable-types-HDBC-pg
- [ ] relational-record

**Comment by juhp** [comment]
It is LTS 22 which was recently released
https://www.stackage.org/lts-22.1/package/product-isomorphic-0.0.3.4

Tell us if you still want lts-21 - though we are not sure yet if there will be any more LTS 21 minor releases

**Comment by juhp** [comment]
Let me close this now, thanks
