### ISSUE TITLE
amazonka-secretsmanager

### ISSUE THREAD

**Issue by ysangkok** [commercialhaskell/lts-haskell#381]
I somehow missed adding amazonka-secretsmanager to nightly when it was still on 9.6. Now it's on 9.8 and amazonka isn't compatible with that, so I can't add it to nightly now.

But this package *is* compatible with GHC 9.6, so it would work in LTS. Would it be possible to add it?

**Comment by juhp** [comment]
Sorry seems we missed/overlooked this for a few weeks, apologies...

**Comment by ysangkok** [comment]
@juhp Is there something I can do to advance this?

**Comment by juhp** [comment]
@jkachmar - if you have time to get this into the next  lts-22.29 that would be great

**Comment by jkachmar** [comment]
resolved in 8ce96ba6bda3aa57151bac44005feeb050953b2f; should be released as part of `lts-22.29`.

i'll hold off on closing this issue until the LTS finishes building & is uploaded to Stackage.

**Comment by jkachmar** [comment]
[included in `lts-22.29`](https://www.stackage.org/lts-22.29/package/amazonka-secretsmanager-2.0)
