### ISSUE TITLE
Add web3 to lts-11

### ISSUE THREAD

**Issue by akru** [commercialhaskell/lts-haskell#87]
## web3
Thanks.

**Comment by mihaimaruseac** [comment]
First it needs to be added to nightly, see the comments at fpco/stackage#3164

**Comment by mihaimaruseac** [comment]
Feel free to reopen once it is added to nightly.

**Comment by akru** [comment]
Hi! It was merged in https://github.com/commercialhaskell/stackage/pull/3635
Could you reopen it, @mihaimaruseac?

**Comment by mihaimaruseac** [comment]
Will be for LTS-11.

**Comment by mihaimaruseac** [comment]
Note that tests are failing with

```
test/Network/Ethereum/Web3/Test/SimpleStorageSpec.hs:1:1: error:
    Exception when trying to run compile-time code:
      test-support/build/contracts/abis/SimpleStorage.json: openFile: does not exist (No such file or directory)
    Code: template-haskell-2.12.0.0:Language.Haskell.TH.Quote.quoteDec
            abiFrom "test-support/build/contracts/abis/SimpleStorage.json"
  |
1 | {-# LANGUAGE DataKinds             #-}
  | ^
```

I'm marking them as expected failure.

**Comment by akru** [comment]
Yes, this test require testbed,
https://github.com/airalab/hs-web3/issues/63

**Comment by mihaimaruseac** [comment]
LTS-11.13 contains `web3`. Thanks.
